Ada: ada::url_pattern_helpers::Tokenizer Class Reference
ada::url_pattern_helpers::Tokenizer Class Reference
#include <url_pattern_helpers.h>
Public Member Functions
Tokenizer (std::string_view new_input, token_policy new_policy)
constexpr void get_next_code_point ()
constexpr void seek_and_get_next_code_point (size_t index)
void add_token (token_type type, size_t next_position, size_t value_position, size_t value_length)
void add_token_with_default_length (token_type type, size_t next_position, size_t value_position)
void add_token_with_defaults (token_type type)
std::optional< errors > process_tokenizing_error (size_t next_position, size_t value_position) ada_warn_unused
Friends
tl::expected< std::vector< token >, errors > tokenize (std::string_view input, token_policy policy)
Detailed Description
Definition at line 106 of file url_pattern_helpers.h.
Constructor & Destructor Documentation
Tokenizer()
ada::url_pattern_helpers::Tokenizer::Tokenizer (std::string_view new_input, token_policy new_policy) inline explicit
Definition at line 108 of file url_pattern_helpers.h.
Referenced by tokenize.
Member Function Documentation
add_token()
void ada::url_pattern_helpers::Tokenizer::add_token (token_type type, size_t next_position, size_t value_position, size_t value_length) inline
Definition at line 403 of file url_pattern_helpers-inl.h.
References ADA_ASSERT_TRUE, and ada::to_string().
Referenced by add_token_with_default_length().
add_token_with_default_length()
void ada::url_pattern_helpers::Tokenizer::add_token_with_default_length (token_type type, size_t next_position, size_t value_position) inline
Definition at line 421 of file url_pattern_helpers-inl.h.
References add_token().
Referenced by add_token_with_defaults(), and process_tokenizing_error().
add_token_with_defaults()
void ada::url_pattern_helpers::Tokenizer::add_token_with_defaults (token_type type) inline
Definition at line 431 of file url_pattern_helpers-inl.h.
References add_token_with_default_length(), and ada::to_string().
get_next_code_point()
void ada::url_pattern_helpers::Tokenizer::get_next_code_point () constexpr
Definition at line 347 of file url_pattern_helpers-inl.h.
References ADA_ASSERT_TRUE.
Referenced by seek_and_get_next_code_point().
process_tokenizing_error()
ada_warn_unused std::optional< errors > ada::url_pattern_helpers::Tokenizer::process_tokenizing_error (size_t next_position, size_t value_position) inline
Definition at line 440 of file url_pattern_helpers-inl.h.
References ADA_ASSERT_TRUE, add_token_with_default_length(), ada::url_pattern_helpers::INVALID_CHAR, ada::url_pattern_helpers::lenient, ada::url_pattern_helpers::strict, and ada::type_error.
seek_and_get_next_code_point()
void ada::url_pattern_helpers::Tokenizer::seek_and_get_next_code_point (size_t index) constexpr
Definition at line 394 of file url_pattern_helpers-inl.h.
References get_next_code_point().
Friends And Related Symbol Documentation
tokenize
tl::expected< std::vector< token >, errors > tokenize (std::string_view input, token_policy policy) friend
Definition at line 437 of file url_pattern_helpers.cpp.
References ada::url_pattern_helpers::ASTERISK, ada::url_pattern_helpers::CHAR, ada::url_pattern_helpers::CLOSE, ada::url_pattern_helpers::END, ada::url_pattern_helpers::ESCAPED_CHAR, ada::url_pattern_helpers::NAME, ada::url_pattern_helpers::OPEN, ada::url_pattern_helpers::OTHER_MODIFIER, ada::url_pattern_helpers::REGEXP, Tokenizer(), and ada::idna::valid_name_code_point().
The documentation for this class was generated from the following files:
include/ada/url_pattern_helpers.h
include/ada/url_pattern_helpers-inl.h