Ada: ada::checkers Namespace Reference
ada::checkers Namespace Reference
Includes the definitions for validation functions.
Functions
bool has_hex_prefix_unsafe (std::string_view input)
bool has_hex_prefix (std::string_view input)
constexpr bool is_digit (char x) noexcept
constexpr char to_lower (char x) noexcept
constexpr bool is_alpha (char x) noexcept
constexpr bool is_windows_drive_letter (std::string_view input) noexcept
constexpr bool is_normalized_windows_drive_letter (std::string_view input) noexcept
ada_really_inline constexpr bool begins_with (std::string_view view, std::string_view prefix)
ada_really_inline ada_constexpr bool is_ipv4 (std::string_view view) noexcept
ada_really_inline constexpr uint8_t path_signature (std::string_view input) noexcept
ada_really_inline constexpr bool verify_dns_length (std::string_view input) noexcept
Variables
static constexpr uint8_t path_signature_table [256]
Detailed Description
Includes the definitions for validation functions.
Function Documentation
begins_with()
ada_really_inline constexpr bool ada::checkers::begins_with (std::string_view view, std::string_view prefix) constexpr
Warning
Will be removed when Ada supports C++20.
Definition at line 56 of file checkers-inl.h.
Referenced by ada::url::get_components(), ada::url::get_href(), ada::parser::parse_url(), and ada::url_aggregator::set_pathname().
has_hex_prefix()
bool ada::checkers::has_hex_prefix (std::string_view input) inline
Check whether a string starts with 0x or 0X.
Definition at line 32 of file checkers-inl.h.
References has_hex_prefix_unsafe().
Referenced by is_ipv4().
has_hex_prefix_unsafe()
bool ada::checkers::has_hex_prefix_unsafe (std::string_view input) inline
Check whether a string starts with 0x or 0X. The function is only safe if input.size() >=2.
See also
has_hex_prefix
Definition at line 15 of file checkers-inl.h.
Referenced by has_hex_prefix().
is_alpha()
constexpr bool ada::checkers::is_alpha (char x) constexpr noexcept
Returns true if the character is an ASCII letter. Equivalent to std::isalpha but more likely to be inlined by the compiler.
Attention
std::isalpha is not constexpr generally.
Definition at line 40 of file checkers-inl.h.
References to_lower().
Referenced by is_normalized_windows_drive_letter(), is_windows_drive_letter(), ada::parser::parse_url(), ada::url::set_protocol(), and ada::url_aggregator::set_protocol().
is_digit()
constexpr bool ada::checkers::is_digit (char x) constexpr noexcept
Check whether x is an ASCII digit. More likely to be inlined than std::isdigit.
Definition at line 36 of file checkers-inl.h.
Referenced by is_ipv4().
is_ipv4()
ada_really_inline ada_constexpr bool ada::checkers::is_ipv4 (std::string_view view) noexcept
Returns true if an input is an ipv4 address.
Optimization opportunity: we have basically identified the last number of the ipv4 if we return true here. We might as well parse it and have at least one number parsed when we get to parse_ipv4.
Optimization opportunity: we have basically identified the last number of the ipv4 if we return true here. We might as well parse it and have at least one number parsed when we get to parse_ipv4.
Definition at line 6 of file checkers.cpp.
References has_hex_prefix(), is_digit(), and ada::unicode::is_lowercase_hex().
is_normalized_windows_drive_letter()
constexpr bool ada::checkers::is_normalized_windows_drive_letter (std::string_view input) inline constexpr noexcept
A normalized Windows drive letter is a Windows drive letter of which the second code point is U+003A (:).
Definition at line 51 of file checkers-inl.h.
References is_alpha().
Referenced by ada::parser::parse_url().
is_windows_drive_letter()
constexpr bool ada::checkers::is_windows_drive_letter (std::string_view input) inline constexpr noexcept
A string starts with a Windows drive letter if all of the following are true:
its length is greater than or equal to 2
its first two code points are a Windows drive letter
its length is 2 or its third code point is U+002F (/), U+005C (), U+003F (?), or U+0023 (#).
https://url.spec.whatwg.org/#start-with-a-windows-drive-letter
Definition at line 44 of file checkers-inl.h.
References is_alpha().
Referenced by ada::parser::parse_url().
path_signature()
ada_really_inline constexpr uint8_t ada::checkers::path_signature (std::string_view input) constexpr noexcept
Returns a bitset. If the first bit is set, then at least one character needs percent encoding. If the second bit is set, a \ is found. If the third bit is set then we have a dot. If the fourth bit is set, then we have a percent character.
to_lower()
constexpr char ada::checkers::to_lower (char x) constexpr noexcept
Assuming that x is an ASCII letter, this function returns the lower case equivalent.
More likely to be inlined by the compiler and constexpr.
Definition at line 38 of file checkers-inl.h.
Referenced by is_alpha().
verify_dns_length()
ada_really_inline constexpr bool ada::checkers::verify_dns_length (std::string_view input) constexpr noexcept
Returns true if the length of the domain name and its labels are according to the specifications. The length of the domain must be 255 octets (253 characters not including the last 2 which are the empty label reserved at the end). When the empty label is included (a dot at the end), the domain name can have 254 characters. The length of a label must be at least 1 and at most 63 characters.
See also
section 3.1. of https://www.rfc-editor.org/rfc/rfc1034
https://www.unicode.org/reports/tr46/#ToASCII
Referenced by ada::url::has_valid_domain(), and ada::url_aggregator::has_valid_domain().
Variable Documentation
path_signature_table
constexpr uint8_t ada::checkers::path_signature_table[256] static constexpr
Initial value:
= {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
Definition at line 30 of file checkers.cpp.