Ada: amalgamate Namespace Reference
amalgamate Namespace Reference
Functions
def doinclude (fid, file, line, origin)
def dofile (fid, prepath, filename)
Variables
SCRIPTPATH = os.path.dirname(os.path.abspath(sys.argv[0]))
PROJECTPATH = os.path.dirname(SCRIPTPATH)
AMALGAMATE_SOURCE_PATH = os.path.join(PROJECTPATH, "src")
AMALGAMATE_INCLUDE_PATH = os.path.join(PROJECTPATH, "include")
AMALGAMATE_OUTPUT_PATH = os.path.join(SCRIPTPATH)
list ALLCFILES = ["ada.cpp"]
list ALLCHEADERS = ["ada.h"]
list found_includes = []
string current_implementation = ''
AMAL_H = os.path.join(AMALGAMATE_OUTPUT_PATH, "ada.h")
AMAL_C = os.path.join(AMALGAMATE_OUTPUT_PATH, "ada.cpp")
DEMOCPP = os.path.join(AMALGAMATE_OUTPUT_PATH, "cpp")
README = os.path.join(AMALGAMATE_OUTPUT_PATH, "README.md")
amal_h = open(AMAL_H, 'w')
file
amal_c = open(AMAL_C, 'w')
zf = zipfile.ZipFile(os.path.join(AMALGAMATE_OUTPUT_PATH,'singleheader.zip'), 'w', zipfile.ZIP_DEFLATED)
Function Documentation
dofile()
def amalgamate.dofile (fid, prepath, filename)
Definition at line 69 of file amalgamate.py.
References doinclude().
Referenced by doinclude().
doinclude()
def amalgamate.doinclude (fid, file, line, origin)
Definition at line 47 of file amalgamate.py.
References dofile().
Referenced by dofile().
Variable Documentation
ALLCFILES
list amalgamate.ALLCFILES = ["ada.cpp"]
Definition at line 38 of file amalgamate.py.
ALLCHEADERS
list amalgamate.ALLCHEADERS = ["ada.h"]
Definition at line 41 of file amalgamate.py.
AMAL_C
amalgamate.AMAL_C = os.path.join(AMALGAMATE_OUTPUT_PATH, "ada.cpp")
Definition at line 110 of file amalgamate.py.
amal_c
amalgamate.amal_c = open(AMAL_C, 'w')
Definition at line 124 of file amalgamate.py.
AMAL_H
amalgamate.AMAL_H = os.path.join(AMALGAMATE_OUTPUT_PATH, "ada.h")
Definition at line 109 of file amalgamate.py.
amal_h
amalgamate.amal_h = open(AMAL_H, 'w')
Definition at line 115 of file amalgamate.py.
AMALGAMATE_INCLUDE_PATH
amalgamate.AMALGAMATE_INCLUDE_PATH = os.path.join(PROJECTPATH, "include")
Definition at line 29 of file amalgamate.py.
AMALGAMATE_OUTPUT_PATH
amalgamate.AMALGAMATE_OUTPUT_PATH = os.path.join(SCRIPTPATH)
Definition at line 33 of file amalgamate.py.
AMALGAMATE_SOURCE_PATH
amalgamate.AMALGAMATE_SOURCE_PATH = os.path.join(PROJECTPATH, "src")
Definition at line 25 of file amalgamate.py.
current_implementation
string amalgamate.current_implementation = ''
Definition at line 45 of file amalgamate.py.
DEMOCPP
amalgamate.DEMOCPP = os.path.join(AMALGAMATE_OUTPUT_PATH, "cpp")
Definition at line 111 of file amalgamate.py.
file
amalgamate.file
Definition at line 116 of file amalgamate.py.
found_includes
list amalgamate.found_includes = []
Definition at line 43 of file amalgamate.py.
PROJECTPATH
amalgamate.PROJECTPATH = os.path.dirname(SCRIPTPATH)
Definition at line 18 of file amalgamate.py.
README
amalgamate.README = os.path.join(AMALGAMATE_OUTPUT_PATH, "README.md")
Definition at line 112 of file amalgamate.py.
SCRIPTPATH
amalgamate.SCRIPTPATH = os.path.dirname(os.path.abspath(sys.argv[0]))
Definition at line 17 of file amalgamate.py.
zf
amalgamate.zf = zipfile.ZipFile(os.path.join(AMALGAMATE_OUTPUT_PATH,'singleheader.zip'), 'w', zipfile.ZIP_DEFLATED)
Definition at line 137 of file amalgamate.py.