Ada: tl::unexpected< E > Class Template Reference
tl::unexpected< E > Class Template Reference
#include <expected.h>
Public Member Functions
unexpected ()=delete
constexpr unexpected (const E &e)
constexpr unexpected (E &&e)
template<class... Args, typename std::enable_if< std::is_constructible< E, Args &&... >::value >::type * = nullptr>
constexpr unexpected (Args &&...args)
template<class U , class... Args, typename std::enable_if< std::is_constructible< E, std::initializer_list< U > &, Args &&... >::value >::type * = nullptr>
constexpr unexpected (std::initializer_list< U > l, Args &&...args)
constexpr const E & value () const &
TL_EXPECTED_11_CONSTEXPR E & value () &
TL_EXPECTED_11_CONSTEXPR E && value () &&
constexpr const E && value () const &&
Detailed Description
template<class E>
class tl::unexpected< E >
Definition at line 132 of file expected.h.
Constructor & Destructor Documentation
unexpected() [1/5]
template<class E > tl::unexpected< E >::unexpected () delete
unexpected() [2/5]
template<class E > constexpr tl::unexpected< E >::unexpected (const E & e) inline explicit constexpr
Definition at line 137 of file expected.h.
unexpected() [3/5]
template<class E > constexpr tl::unexpected< E >::unexpected (E && e) inline explicit constexpr
Definition at line 139 of file expected.h.
unexpected() [4/5]
template<class E > template<class... Args, typename std::enable_if< std::is_constructible< E, Args &&... >::value >::type * = nullptr> constexpr tl::unexpected< E >::unexpected (Args &&... args) inline explicit constexpr
Definition at line 143 of file expected.h.
unexpected() [5/5]
template<class E > template<class U , class... Args, typename std::enable_if< std::is_constructible< E, std::initializer_list< U > &, Args &&... >::value >::type * = nullptr> constexpr tl::unexpected< E >::unexpected (std::initializer_list< U > l, Args &&... args) inline explicit constexpr
Definition at line 149 of file expected.h.
Member Function Documentation
value() [1/4]
template<class E > TL_EXPECTED_11_CONSTEXPR E& tl::unexpected< E >::value () & inline
Definition at line 153 of file expected.h.
value() [2/4]
template<class E > TL_EXPECTED_11_CONSTEXPR E&& tl::unexpected< E >::value () && inline
Definition at line 154 of file expected.h.
value() [3/4]
template<class E > constexpr const E& tl::unexpected< E >::value () const & inline constexpr
Definition at line 152 of file expected.h.
Referenced by tl::operator!=(), tl::operator<(), tl::operator<=(), tl::operator==(), tl::operator>(), and tl::operator>=().
value() [4/4]
template<class E > constexpr const E&& tl::unexpected< E >::value () const && inline constexpr
Definition at line 155 of file expected.h.
The documentation for this class was generated from the following file:
include/ada/expected.h