Ada: tl Namespace Reference
tl Namespace Reference
Namespaces
detail
Classes
class expected
class monostate
struct in_place_t
class unexpected
struct unexpect_t
class bad_expected_access
Functions
template<class E >
constexpr bool operator== (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
constexpr bool operator!= (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
constexpr bool operator< (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
constexpr bool operator<= (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
constexpr bool operator> (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
constexpr bool operator>= (const unexpected< E > &lhs, const unexpected< E > &rhs)
template<class E >
unexpected< typename std::decay< E >::type > make_unexpected (E &&e)
template<class T , class E , class U , class F >
constexpr bool operator== (const expected< T, E > &lhs, const expected< U, F > &rhs)
template<class T , class E , class U , class F >
constexpr bool operator!= (const expected< T, E > &lhs, const expected< U, F > &rhs)
template<class E , class F >
constexpr bool operator== (const expected< void, E > &lhs, const expected< void, F > &rhs)
template<class E , class F >
constexpr bool operator!= (const expected< void, E > &lhs, const expected< void, F > &rhs)
template<class T , class E , class U >
constexpr bool operator== (const expected< T, E > &x, const U &v)
template<class T , class E , class U >
constexpr bool operator== (const U &v, const expected< T, E > &x)
template<class T , class E , class U >
constexpr bool operator!= (const expected< T, E > &x, const U &v)
template<class T , class E , class U >
constexpr bool operator!= (const U &v, const expected< T, E > &x)
template<class T , class E >
constexpr bool operator== (const expected< T, E > &x, const unexpected< E > &e)
template<class T , class E >
constexpr bool operator== (const unexpected< E > &e, const expected< T, E > &x)
template<class T , class E >
constexpr bool operator!= (const expected< T, E > &x, const unexpected< E > &e)
template<class T , class E >
constexpr bool operator!= (const unexpected< E > &e, const expected< T, E > &x)
template<class T , class E , detail::enable_if_t<(std::is_void< T >::value||std::is_move_constructible< T >::value) &&detail::is_swappable< T >::value &&std::is_move_constructible< E >::value &&detail::is_swappable< E >::value > * = nullptr>
void swap (expected< T, E > &lhs, expected< T, E > &rhs) noexcept(noexcept(lhs.swap(rhs)))
Variables
static constexpr in_place_t in_place {}
static constexpr unexpect_t unexpect {}
Function Documentation
make_unexpected()
template<class E > unexpected<typename std::decay<E>::type> tl::make_unexpected (E && e)
Definition at line 191 of file expected.h.
operator!=() [1/7]
template<class T , class E , class U , class F > constexpr bool tl::operator!= (const expected< T, E > & lhs, const expected< U, F > & rhs) constexpr
Definition at line 2301 of file expected.h.
References tl::expected< T, E >::error(), and tl::expected< T, E >::has_value().
operator!=() [2/7]
template<class T , class E , class U > constexpr bool tl::operator!= (const expected< T, E > & x, const U & v) constexpr
Definition at line 2331 of file expected.h.
References tl::expected< T, E >::has_value().
operator!=() [3/7]
template<class T , class E > constexpr bool tl::operator!= (const expected< T, E > & x, const unexpected< E > & e) constexpr
Definition at line 2348 of file expected.h.
References tl::expected< T, E >::error(), tl::expected< T, E >::has_value(), and tl::unexpected< E >::value().
operator!=() [4/7]
template<class E , class F > constexpr bool tl::operator!= (const expected< void, E > & lhs, const expected< void, F > & rhs) constexpr
Definition at line 2315 of file expected.h.
References tl::expected< T, E >::error(), and tl::expected< T, E >::has_value().
operator!=() [5/7]
template<class T , class E , class U > constexpr bool tl::operator!= (const U & v, const expected< T, E > & x) constexpr
Definition at line 2335 of file expected.h.
References tl::expected< T, E >::has_value().
operator!=() [6/7]
template<class T , class E > constexpr bool tl::operator!= (const unexpected< E > & e, const expected< T, E > & x) constexpr
Definition at line 2352 of file expected.h.
References tl::expected< T, E >::error(), tl::expected< T, E >::has_value(), and tl::unexpected< E >::value().
operator!=() [7/7]
template<class E > constexpr bool tl::operator!= (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 170 of file expected.h.
References tl::unexpected< E >::value().
operator<()
template<class E > constexpr bool tl::operator< (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 174 of file expected.h.
References tl::unexpected< E >::value().
operator<=()
template<class E > constexpr bool tl::operator<= (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 178 of file expected.h.
References tl::unexpected< E >::value().
operator==() [1/7]
template<class T , class E , class U , class F > constexpr bool tl::operator== (const expected< T, E > & lhs, const expected< U, F > & rhs) constexpr
Definition at line 2294 of file expected.h.
References tl::expected< T, E >::error(), and tl::expected< T, E >::has_value().
operator==() [2/7]
template<class T , class E , class U > constexpr bool tl::operator== (const expected< T, E > & x, const U & v) constexpr
Definition at line 2323 of file expected.h.
References tl::expected< T, E >::has_value().
operator==() [3/7]
template<class T , class E > constexpr bool tl::operator== (const expected< T, E > & x, const unexpected< E > & e) constexpr
Definition at line 2340 of file expected.h.
References tl::expected< T, E >::error(), tl::expected< T, E >::has_value(), and tl::unexpected< E >::value().
operator==() [4/7]
template<class E , class F > constexpr bool tl::operator== (const expected< void, E > & lhs, const expected< void, F > & rhs) constexpr
Definition at line 2308 of file expected.h.
References tl::expected< T, E >::error(), and tl::expected< T, E >::has_value().
operator==() [5/7]
template<class T , class E , class U > constexpr bool tl::operator== (const U & v, const expected< T, E > & x) constexpr
Definition at line 2327 of file expected.h.
References tl::expected< T, E >::has_value().
operator==() [6/7]
template<class T , class E > constexpr bool tl::operator== (const unexpected< E > & e, const expected< T, E > & x) constexpr
Definition at line 2344 of file expected.h.
References tl::expected< T, E >::error(), tl::expected< T, E >::has_value(), and tl::unexpected< E >::value().
operator==() [7/7]
template<class E > constexpr bool tl::operator== (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 166 of file expected.h.
References tl::unexpected< E >::value().
operator>()
template<class E > constexpr bool tl::operator> (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 182 of file expected.h.
References tl::unexpected< E >::value().
operator>=()
template<class E > constexpr bool tl::operator>= (const unexpected< E > & lhs, const unexpected< E > & rhs) constexpr
Definition at line 186 of file expected.h.
References tl::unexpected< E >::value().
swap()
template<class T , class E , detail::enable_if_t<(std::is_void< T >::value||std::is_move_constructible< T >::value) &&detail::is_swappable< T >::value &&std::is_move_constructible< E >::value &&detail::is_swappable< E >::value > * = nullptr> void tl::swap (expected< T, E > & lhs, expected< T, E > & rhs) noexcept
Definition at line 2362 of file expected.h.
References tl::expected< T, E >::swap().
Referenced by tl::expected< T, E >::swap().
Variable Documentation
in_place
constexpr in_place_t tl::in_place {} static constexpr
Definition at line 129 of file expected.h.
unexpect
constexpr unexpect_t tl::unexpect {} static constexpr
Definition at line 198 of file expected.h.
Referenced by tl::detail::and_then_impl(), tl::detail::expected_map_impl(), and tl::detail::map_error_impl().