Ada: tl::detail::expected_operations_base< void, E > Struct Template Reference
tl::detail::expected_operations_base< void, E > Struct Template Reference
#include <expected.h>
Public Member Functions
template<class... Args>
void construct () noexcept
template<class Rhs >
void construct_with (Rhs &&) noexcept
template<class... Args>
void construct_error (Args &&...args) noexcept
template<class Rhs >
void assign (Rhs &&rhs) noexcept
bool has_value () const
TL_EXPECTED_11_CONSTEXPR unexpected< E > & geterr () &
constexpr const unexpected< E > & geterr () const &
TL_EXPECTED_11_CONSTEXPR unexpected< E > && geterr () &&
constexpr const unexpected< E > && geterr () const &&
TL_EXPECTED_11_CONSTEXPR void destroy_val ()
Public Member Functions inherited from tl::detail::expected_storage_base< void, E >
constexpr expected_storage_base ()
constexpr expected_storage_base (no_init_t)
constexpr expected_storage_base (in_place_t, Args &&...args)
constexpr expected_storage_base (in_place_t, std::initializer_list< U > il, Args &&...args)
constexpr expected_storage_base (unexpect_t, Args &&...args)
constexpr expected_storage_base (unexpect_t, std::initializer_list< U > il, Args &&...args)
~expected_storage_base ()
Additional Inherited Members
Public Attributes inherited from tl::detail::expected_storage_base< void, E >
void m_val
unexpected< E > m_unexpect
char m_no_init
union {
T m_val
unexpected< E > m_unexpect
char m_no_init
};
bool m_has_val
Detailed Description
template<class E>
struct tl::detail::expected_operations_base< void, E >
Definition at line 872 of file expected.h.
Member Function Documentation
assign()
template<class E > template<class Rhs > void tl::detail::expected_operations_base< void, E >::assign (Rhs && rhs) inline noexcept
Definition at line 889 of file expected.h.
References tl::detail::expected_operations_base< T, E >::construct(), tl::detail::expected_operations_base< T, E >::construct_error(), tl::detail::expected_operations_base< T, E >::geterr(), and tl::detail::expected_storage_base< T, E, bool, bool >::m_has_val.
construct()
template<class E > template<class... Args> void tl::detail::expected_operations_base< void, E >::construct () inline noexcept
Definition at line 875 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_has_val.
construct_error()
template<class E > template<class... Args> void tl::detail::expected_operations_base< void, E >::construct_error (Args &&... args) inline noexcept
Definition at line 883 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_has_val, and tl::detail::expected_storage_base< T, E, bool, bool >::m_unexpect.
construct_with()
template<class E > template<class Rhs > void tl::detail::expected_operations_base< void, E >::construct_with (Rhs &&) inline noexcept
Definition at line 879 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_has_val.
destroy_val()
template<class E > TL_EXPECTED_11_CONSTEXPR void tl::detail::expected_operations_base< void, E >::destroy_val () inline
Definition at line 919 of file expected.h.
geterr() [1/4]
template<class E > TL_EXPECTED_11_CONSTEXPR unexpected<E>& tl::detail::expected_operations_base< void, E >::geterr () & inline
Definition at line 906 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_unexpect.
geterr() [2/4]
template<class E > TL_EXPECTED_11_CONSTEXPR unexpected<E>&& tl::detail::expected_operations_base< void, E >::geterr () && inline
Definition at line 910 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_unexpect.
geterr() [3/4]
template<class E > constexpr const unexpected<E>& tl::detail::expected_operations_base< void, E >::geterr () const & inline constexpr
Definition at line 909 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_unexpect.
geterr() [4/4]
template<class E > constexpr const unexpected<E>&& tl::detail::expected_operations_base< void, E >::geterr () const && inline constexpr
Definition at line 914 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_unexpect.
has_value()
template<class E > bool tl::detail::expected_operations_base< void, E >::has_value () const inline
Definition at line 904 of file expected.h.
References tl::detail::expected_storage_base< T, E, bool, bool >::m_has_val.
The documentation for this struct was generated from the following file:
include/ada/expected.h