Ada: fuzz/ada_c.c File Reference
ada_c.c File Reference
#include "ada_c.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
ada_c
Definition at line 8 of file ada_c.c.
References ada_can_parse(), ada_clear_hash(), ada_clear_port(), ada_clear_search(), ada_free(), ada_free_owned_string(), ada_get_components(), ada_get_hash(), ada_get_host(), ada_get_host_type(), ada_get_hostname(), ada_get_href(), ada_get_origin(), ada_get_password(), ada_get_pathname(), ada_get_port(), ada_get_protocol(), ada_get_scheme_type(), ada_get_search(), ada_get_username(), ada_has_credentials(), ada_has_empty_hostname(), ada_has_hash(), ada_has_hostname(), ada_has_non_empty_password(), ada_has_non_empty_username(), ada_has_password(), ada_has_port(), ada_has_search(), ada_is_valid(), ada_parse(), ada_set_hash(), ada_set_host(), ada_set_hostname(), ada_set_href(), ada_set_password(), ada_set_pathname(), ada_set_port(), ada_set_protocol(), ada_set_search(), and ada_set_username().