Ada: ada::url_pattern_compile_component_options Struct Reference
ada::url_pattern_compile_component_options Struct Reference
#include <url_pattern.h>
Public Member Functions
url_pattern_compile_component_options ()=default
url_pattern_compile_component_options (std::optional< char > new_delimiter=std::nullopt, std::optional< char > new_prefix=std::nullopt)
std::string_view get_delimiter () const ada_warn_unused
std::string_view get_prefix () const ada_warn_unused
Public Attributes
bool ignore_case = false
Static Public Attributes
static url_pattern_compile_component_options DEFAULT
static url_pattern_compile_component_options HOSTNAME
static url_pattern_compile_component_options PATHNAME
Detailed Description
Definition at line 87 of file url_pattern.h.
Constructor & Destructor Documentation
url_pattern_compile_component_options() [1/2]
ada::url_pattern_compile_component_options::url_pattern_compile_component_options () default
url_pattern_compile_component_options() [2/2]
ada::url_pattern_compile_component_options::url_pattern_compile_component_options (std::optional< char > new_delimiter = std::nullopt, std::optional< char > new_prefix = std::nullopt) inline explicit
Definition at line 89 of file url_pattern.h.
Member Function Documentation
get_delimiter()
std::string_view ada::url_pattern_compile_component_options::get_delimiter () const inline
Definition at line 124 of file url_pattern-inl.h.
Referenced by ada::url_pattern_helpers::generate_segment_wildcard_regexp().
get_prefix()
std::string_view ada::url_pattern_compile_component_options::get_prefix () const inline
Definition at line 132 of file url_pattern-inl.h.
Referenced by ada::url_pattern_helpers::generate_pattern_string(), and ada::url_pattern_helpers::parse_pattern_string().
Member Data Documentation
DEFAULT
url_pattern_compile_component_options ada::url_pattern_compile_component_options::DEFAULT inline static
Definition at line 100 of file url_pattern.h.
Referenced by ada::url_pattern_helpers::constructor_string_parser< regex_provider >::compute_protocol_matches_special_scheme_flag(), and ada::url_aggregator::parse_url_pattern_impl.
HOSTNAME
url_pattern_compile_component_options ada::url_pattern_compile_component_options::HOSTNAME inline static
Definition at line 101 of file url_pattern.h.
Referenced by ada::url_aggregator::parse_url_pattern_impl.
ignore_case
bool ada::url_pattern_compile_component_options::ignore_case = false
Definition at line 98 of file url_pattern.h.
Referenced by ada::url_pattern_component< regex_provider >::compile().
PATHNAME
url_pattern_compile_component_options ada::url_pattern_compile_component_options::PATHNAME inline static
Definition at line 102 of file url_pattern.h.
Referenced by ada::url_aggregator::parse_url_pattern_impl.
The documentation for this struct was generated from the following files:
include/ada/url_pattern.h
include/ada/url_pattern-inl.h