Ada: ada::helpers Namespace Reference
ada::helpers Namespace Reference
Includes the definitions for helper functions.
Functions
ada_really_inline std::optional< std::string_view > prune_fragment (std::string_view &input) noexcept
ada_really_inline void shorten_path (std::string &path, ada::scheme::type type) noexcept
ada_really_inline void remove_ascii_tab_or_newline (std::string &input) noexcept
ada_really_inline std::string_view substring (std::string_view input, size_t pos) noexcept
ada_really_inline std::pair< size_t, bool > get_host_delimiter_location (const bool is_special, std::string_view &view) noexcept
ada_really_inline void trim_c0_whitespace (std::string_view &input) noexcept
ada_really_inline void strip_trailing_spaces_from_opaque_path (ada::url &url) noexcept
ada_really_inline uint64_t swap_bytes (uint64_t val) noexcept
ada_really_inline uint64_t swap_bytes_if_big_endian (uint64_t val) noexcept
ada_really_inline size_t find_authority_delimiter_special (std::string_view view) noexcept
ada_really_inline size_t find_authority_delimiter (std::string_view view) noexcept
template<typename out_iter >
void encode_json (std::string_view view, out_iter out)
ada_unused std::string get_state (ada::state s)
ada_really_inline size_t find_next_host_delimiter_special (std::string_view view, size_t location) noexcept
ada_really_inline size_t find_next_host_delimiter (std::string_view view, size_t location) noexcept
Detailed Description
Includes the definitions for helper functions.
Function Documentation
encode_json()
template<typename out_iter > void ada::helpers::encode_json (std::string_view view, out_iter out)
Definition at line 14 of file helpers.cpp.
Referenced by ada::url::to_string().
find_authority_delimiter()
ada_really_inline size_t ada::helpers::find_authority_delimiter (std::string_view view) noexcept
Finds the delimiter of a view in authority state.
Definition at line 495 of file helpers.cpp.
References swap_bytes_if_big_endian().
Referenced by ada::parser::parse_url().
find_authority_delimiter_special()
ada_really_inline size_t ada::helpers::find_authority_delimiter_special (std::string_view view) noexcept
Finds the delimiter of a view in authority state.
Definition at line 450 of file helpers.cpp.
References swap_bytes_if_big_endian().
Referenced by ada::parser::parse_url().
find_next_host_delimiter()
ada_really_inline size_t ada::helpers::find_next_host_delimiter (std::string_view view, size_t location) noexcept
Definition at line 181 of file helpers.cpp.
References swap_bytes_if_big_endian().
Referenced by get_host_delimiter_location().
find_next_host_delimiter_special()
ada_really_inline size_t ada::helpers::find_next_host_delimiter_special (std::string_view view, size_t location) noexcept
Definition at line 124 of file helpers.cpp.
References swap_bytes_if_big_endian().
Referenced by get_host_delimiter_location().
get_host_delimiter_location()
ada_really_inline std::pair< size_t, bool > ada::helpers::get_host_delimiter_location (const bool is_special, std::string_view & view) noexcept
Returns a host's delimiter location depending on the state of the instance, and whether a colon was found outside brackets. Used by the host parser.
The spec at https://url.spec.whatwg.org/#hostname-state expects us to compute a variable called insideBrackets but this variable is only used once, to check whether a ':' character was found outside brackets. Exact text: "Otherwise, if c is U+003A (:) and insideBrackets is false, then:". It is conceptually simpler and arguably more efficient to just return a Boolean indicating whether ':' was found outside brackets.
Performance analysis:
We are basically seeking the end of the hostname which can be indicated by the end of the view, or by one of the characters ':', '/', '?', '\' (where '\' is only applicable for special URLs). However, these must appear outside a bracket range. E.g., if you have [something?]fd: then the '?' does not count.
So we can skip ahead to the next delimiter, as long as we include '[' in the set of delimiters, and that we handle it first.
So the trick is to have a fast function that locates the next delimiter. Unless we find '[', then it only needs to be called once! Ideally, such a function would be provided by the C++ standard library, but it seems that find_first_of is not very fast, so we are forced to roll our own.
We do not break into two loops for speed, but for clarity.
The spec at https://url.spec.whatwg.org/#hostname-state expects us to compute a variable called insideBrackets but this variable is only used once, to check whether a ':' character was found outside brackets. Exact text: "Otherwise, if c is U+003A (:) and insideBrackets is false, then:". It is conceptually simpler and arguably more efficient to just return a Boolean indicating whether ':' was found outside brackets.
Performance analysis:
We are basically seeking the end of the hostname which can be indicated by the end of the view, or by one of the characters ':', '/', '?', '\' (where '\' is only applicable for special URLs). However, these must appear outside a bracket range. E.g., if you have [something?]fd: then the '?' does not count.
So we can skip ahead to the next delimiter, as long as we include '[' in the set of delimiters, and that we handle it first.
So the trick is to have a fast function that locates the next delimiter. Unless we find '[', then it only needs to be called once! Ideally, such a function would be provided by the C++ standard library, but it seems that find_first_of is not very fast, so we are forced to roll our own.
We do not break into two loops for speed, but for clarity.
Definition at line 233 of file helpers.cpp.
References find_next_host_delimiter(), find_next_host_delimiter_special(), and ada::scheme::is_special().
Referenced by ada::parser::parse_url().
get_state()
ada_unused std::string ada::helpers::get_state (ada::state s)
Definition at line 32 of file helpers.cpp.
References ada::AUTHORITY, ada::FILE, ada::FILE_HOST, ada::FILE_SLASH, ada::FRAGMENT, ada::HOST, ada::NO_SCHEME, ada::OPAQUE_PATH, ada::PATH, ada::PATH_OR_AUTHORITY, ada::PATH_START, ada::PORT, ada::QUERY, ada::RELATIVE_SCHEME, ada::RELATIVE_SLASH, ada::SCHEME, ada::SCHEME_START, ada::SPECIAL_AUTHORITY_IGNORE_SLASHES, ada::SPECIAL_AUTHORITY_SLASHES, and ada::SPECIAL_RELATIVE_OR_AUTHORITY.
Referenced by ada::to_string().
prune_fragment()
ada_really_inline std::optional< std::string_view > ada::helpers::prune_fragment (std::string_view & input) noexcept
This function is used to prune a fragment from a url, and returning the removed string if input has fragment.
prune_fragment seeks the first '#' and returns everything after it as a string_view, and modifies (in place) the input so that it points at everything before the '#'. If no '#' is found, the input is left unchanged and std::nullopt is returned.
Attention
The function is non-allocating and it does not throw.
Returns
Note that the returned string_view might be empty!
Definition at line 58 of file helpers.cpp.
Referenced by ada::parser::parse_url().
remove_ascii_tab_or_newline()
ada_really_inline void ada::helpers::remove_ascii_tab_or_newline (std::string & input) noexcept
Remove and mutate all ASCII tab or newline characters from an input.
Definition at line 86 of file helpers.cpp.
Referenced by ada::href_from_file(), ada::parser::parse_url(), ada::url::set_hash(), ada::url::set_port(), ada::url::set_protocol(), and ada::url::set_search().
shorten_path()
ada_really_inline void ada::helpers::shorten_path (std::string & path, ada::scheme::type type) noexcept
Defined by the URL specification, shorten a URLs paths.
See also
https://url.spec.whatwg.org/#shorten-a-urls-path
Definition at line 69 of file helpers.cpp.
References ada::scheme::FILE, and ada::checkers::is_normalized_windows_drive_letter().
Referenced by ada::parser::parse_url().
strip_trailing_spaces_from_opaque_path()
ada_really_inline void ada::helpers::strip_trailing_spaces_from_opaque_path (ada::url & url) noexcept
See also
https://url.spec.whatwg.org/#potentially-strip-trailing-spaces-from-an-opaque-path
Definition at line 443 of file helpers.cpp.
References ada::url::has_opaque_path.
Referenced by ada::url::set_hash(), and ada::url::set_search().
substring()
ada_really_inline std::string_view ada::helpers::substring (std::string_view input, size_t pos) noexcept
Return the substring from input going from index pos to the end. If pos > input.size(), it returns an empty string_view. This function cannot throw.
Definition at line 93 of file helpers.cpp.
Referenced by ada::parser::parse_url().
swap_bytes()
ada_really_inline uint64_t ada::helpers::swap_bytes (uint64_t val) noexcept
Reverse the order of the bytes.
Definition at line 99 of file helpers.cpp.
Referenced by swap_bytes_if_big_endian().
swap_bytes_if_big_endian()
ada_really_inline uint64_t ada::helpers::swap_bytes_if_big_endian (uint64_t val) noexcept
Reverse the order of the bytes but only if the system is big endian
Definition at line 111 of file helpers.cpp.
References swap_bytes().
Referenced by find_authority_delimiter(), find_authority_delimiter_special(), find_next_host_delimiter(), and find_next_host_delimiter_special().
trim_c0_whitespace()
ada_really_inline void ada::helpers::trim_c0_whitespace (std::string_view & input) noexcept
Removes leading and trailing C0 control and whitespace characters from string.
Definition at line 310 of file helpers.cpp.
References ada::unicode::is_c0_control_or_space().
Referenced by ada::parser::parse_url().