Ada: ada::url Struct Reference
ada::url Struct Reference
Generic URL struct reliant on std::string instantiation.
#include <url.h>
Public Member Functions
url ()=default
url (const url &u)=default
url (url &&u) noexcept=default
url & operator= (url &&u) noexcept=default
url & operator= (const url &u)=default
~url ()=default
bool has_empty_hostname () const noexcept
bool has_port () const noexcept
bool has_hostname () const noexcept
bool has_valid_domain () const noexcept override
std::string to_string () const override
ada_really_inline std::string get_href () const noexcept
std::string get_origin () const noexcept override
std::string get_protocol () const noexcept
std::string get_host () const noexcept
std::string get_hostname () const noexcept
const std::string_view get_pathname () const noexcept
ada_really_inline size_t get_pathname_length () const noexcept
std::string get_search () const noexcept
const std::string & get_username () const noexcept
bool set_username (const std::string_view input)
bool set_password (const std::string_view input)
bool set_port (const std::string_view input)
void set_hash (const std::string_view input)
void set_search (const std::string_view input)
bool set_pathname (const std::string_view input)
bool set_host (const std::string_view input)
bool set_hostname (const std::string_view input)
bool set_protocol (const std::string_view input)
bool set_href (const std::string_view input)
const std::string & get_password () const noexcept
std::string get_port () const noexcept
std::string get_hash () const noexcept
ada_really_inline bool has_credentials () const noexcept
ada_really_inline ada::url_components get_components () const noexcept
bool has_hash () const noexcept override
bool has_search () const noexcept override
Public Member Functions inherited from ada::url_base
virtual ~url_base ()=default
ada_really_inline bool is_special () const noexcept
virtual std::string get_origin () const noexcept=0
virtual bool has_valid_domain () const noexcept=0
virtual std::string to_string () const =0
Friends
ada::url ada::parser::parse_url (std::string_view, const ada::url *)
ada::url_aggregator ada::parser::parse_url (std::string_view, const ada::url_aggregator *)
void ada::helpers::strip_trailing_spaces_from_opaque_path (ada::url &url) noexcept
Additional Inherited Members
Public Attributes inherited from ada::url_base
bool is_valid {true}
bool has_opaque_path {false}
Detailed Description
Generic URL struct reliant on std::string instantiation.
To disambiguate from a valid URL string it can also be referred to as a URL record. A URL is a struct that represents a universal identifier. Unlike the url_aggregator, the ada::url represents the different components of a parsed URL as independent std::string instances. This makes the structure heavier and more reliant on memory allocations. When getting components from the parsed URL, a new std::string is typically constructed.
See also
https://url.spec.whatwg.org/#url-representation
Definition at line 38 of file url.h.
Constructor & Destructor Documentation
url() [1/3]
ada::url::url () default
url() [2/3]
ada::url::url (const url & u) default
url() [3/3]
ada::url::url (url && u) default noexcept
~url()
ada::url::~url () default
Member Function Documentation
get_components()
ada_really_inline ada::url_components ada::url::get_components () const noexcept
Useful for implementing efficient serialization for the URL.
https://user:pass@example.com:1234/foo/bar?baz#quux | | | | ^^^^| | | | | | | | | | ----- hash_start | | | | | |------— search_start | | | | | ----------------- pathname_start | | | |------------------— port | | | ----------------------- host_end | |-------------------------------— host_start | --------------------------------------- username_end ------------------------------------------— protocol_end
Inspired after servo/url
Returns
a newly constructed component.
See also
https://github.com/servo/rust-url/blob/b65a45515c10713f6d212e6726719a020203cc98/url/src/quirks.rs#L31
Definition at line 44 of file url-inl.h.
References ada::checkers::begins_with(), ada::helpers::fast_digit_count(), get_protocol(), get_search(), has_credentials(), ada::url_base::has_opaque_path, and ada::url_components::protocol_end.
get_hash()
std::string ada::url::get_hash () const noexcept
Return U+0023 (#), followed by this’s URL’s fragment.
Returns
a newly constructed string representing the hash.
See also
https://url.spec.whatwg.org/#dom-url-hash
Definition at line 89 of file url-getters.cpp.
get_host()
std::string ada::url::get_host () const noexcept
Return url’s host, serialized, followed by U+003A (:) and url’s port, serialized. When there is no host, this function returns the empty string.
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#dom-url-host
Definition at line 48 of file url-getters.cpp.
References get_port().
Referenced by get_origin().
get_hostname()
std::string ada::url::get_hostname () const noexcept
Return this’s URL’s host, serialized. When there is no host, this function returns the empty string.
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#dom-url-hostname
Definition at line 62 of file url-getters.cpp.
Referenced by ada::parser::parse_url().
get_href()
ada_really_inline std::string ada::url::get_href () const noexcept
See also
https://url.spec.whatwg.org/#dom-url-href
https://url.spec.whatwg.org/#concept-url-serializer
Definition at line 181 of file url-inl.h.
References ada::checkers::begins_with(), get_password(), get_port(), get_protocol(), has_credentials(), and ada::url_base::has_opaque_path.
Referenced by ada::parser::parse_url().
get_origin()
std::string ada::url::get_origin () const override virtual noexcept
The origin getter steps are to return the serialization of this’s URL’s origin. [HTML]
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#concept-url-origin
Implements ada::url_base.
Definition at line 14 of file url-getters.cpp.
References ada::helpers::concat(), ada::scheme::FILE, get_host(), get_protocol(), ada::scheme::HTTP, ada::scheme::HTTPS, and ada::url_base::is_special().
get_password()
const std::string & ada::url::get_password () const noexcept
The password getter steps are to return this’s URL’s password.
Returns
a constant reference to the underlying string.
See also
https://url.spec.whatwg.org/#dom-url-password
Definition at line 81 of file url-getters.cpp.
Referenced by get_href().
get_pathname()
const std::string_view ada::url::get_pathname () const noexcept
The pathname getter steps are to return the result of URL path serializing this’s URL.
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#dom-url-pathname
Definition at line 66 of file url-getters.cpp.
Referenced by ada::parser::parse_url().
get_pathname_length()
size_t ada::url::get_pathname_length () const noexcept
Compute the pathname length in bytes without instantiating a view or a string.
Returns
size of the pathname in bytes
See also
https://url.spec.whatwg.org/#dom-url-pathname
Definition at line 42 of file url-inl.h.
get_port()
std::string ada::url::get_port () const noexcept
Return this’s URL’s port, serialized.
Returns
a newly constructed string representing the port.
See also
https://url.spec.whatwg.org/#dom-url-port
Definition at line 85 of file url-getters.cpp.
Referenced by get_host(), and get_href().
get_protocol()
std::string ada::url::get_protocol () const noexcept
The protocol getter steps are to return this’s URL’s scheme, followed by U+003A (:).
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#dom-url-protocol
Definition at line 40 of file url-getters.cpp.
References ada::helpers::concat(), ada::url_base::is_special(), and ada::scheme::details::is_special_list.
Referenced by get_components(), get_href(), get_origin(), ada::parser::parse_url(), and to_string().
get_search()
std::string ada::url::get_search () const noexcept
Return U+003F (?), followed by this’s URL’s query.
Returns
a newly allocated string.
See also
https://url.spec.whatwg.org/#dom-url-search
Definition at line 70 of file url-getters.cpp.
Referenced by get_components().
get_username()
const std::string & ada::url::get_username () const noexcept
The username getter steps are to return this’s URL’s username.
Returns
a constant reference to the underlying string.
See also
https://url.spec.whatwg.org/#dom-url-username
Definition at line 77 of file url-getters.cpp.
has_credentials()
ada_really_inline bool ada::url::has_credentials () const noexcept
A URL includes credentials if its username or password is not the empty string.
Definition at line 19 of file url-inl.h.
Referenced by get_components(), get_href(), and to_string().
has_empty_hostname()
bool ada::url::has_empty_hostname () const inline noexcept
Returns
true if it has an host but it is the empty string
Definition at line 29 of file url-inl.h.
has_hash()
bool ada::url::has_hash () const inline override virtual noexcept
Returns
true if the URL has a hash component
Implements ada::url_base.
Definition at line 153 of file url-inl.h.
has_hostname()
bool ada::url::has_hostname () const inline noexcept
Returns
true if it has a host (included an empty host)
Definition at line 35 of file url-inl.h.
has_port()
ada_really_inline bool ada::url::has_port () const inline noexcept
Returns
true if the URL has a (non default) port
Definition at line 22 of file url-inl.h.
has_search()
bool ada::url::has_search () const inline override virtual noexcept
Returns
true if the URL has a search component
Implements ada::url_base.
Definition at line 157 of file url-inl.h.
Referenced by to_string().
has_valid_domain()
bool ada::url::has_valid_domain () const override virtual noexcept
Returns true if this URL has a valid domain as per RFC 1034 and corresponding specifications. Among other things, it requires that the domain string has fewer than 255 octets.
Implements ada::url_base.
Definition at line 581 of file url.cpp.
References ada::checkers::verify_dns_length().
operator=() [1/2]
url & ada::url::operator= (const url & u) default
operator=() [2/2]
url & ada::url::operator= (url && u) default noexcept
set_hash()
void ada::url::set_hash (const std::string_view input)
This function always succeeds.
See also
https://url.spec.whatwg.org/#dom-url-hash
Definition at line 151 of file url-setters.cpp.
References ada::character_sets::FRAGMENT_PERCENT_ENCODE, and ada::unicode::percent_encode().
set_host()
bool ada::url::set_host (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-host
Definition at line 95 of file url-setters.cpp.
Referenced by ada::parser::parse_url().
set_hostname()
bool ada::url::set_hostname (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-hostname
Definition at line 99 of file url-setters.cpp.
Referenced by ada::parser::parse_url().
set_href()
bool ada::url::set_href (const std::string_view input)
See also
https://url.spec.whatwg.org/#dom-url-href
Definition at line 218 of file url-setters.cpp.
References ada::url_base::has_opaque_path.
set_password()
bool ada::url::set_password (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-password
Definition at line 112 of file url-setters.cpp.
References ada::unicode::percent_encode(), and ada::character_sets::USERINFO_PERCENT_ENCODE.
set_pathname()
bool ada::url::set_pathname (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-search
Definition at line 185 of file url-setters.cpp.
References ada::url_base::has_opaque_path.
set_port()
bool ada::url::set_port (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-port
Definition at line 121 of file url-setters.cpp.
References ada::unicode::is_c0_control_or_space(), and ada::url_base::is_valid.
set_protocol()
bool ada::url::set_protocol (const std::string_view input)
Returns
Returns true on success.
See also
https://url.spec.whatwg.org/#dom-url-protocol
Definition at line 194 of file url-setters.cpp.
References ada::unicode::is_alnum_plus(), and ada::checkers::is_alpha().
set_search()
void ada::url::set_search (const std::string_view input)
This function always succeeds.
See also
https://url.spec.whatwg.org/#dom-url-search
Definition at line 166 of file url-setters.cpp.
References ada::url_base::is_special(), ada::unicode::percent_encode(), ada::character_sets::QUERY_PERCENT_ENCODE, and ada::character_sets::SPECIAL_QUERY_PERCENT_ENCODE.
set_username()
bool ada::url::set_username (const std::string_view input)
Returns
Returns true on successful operation.
See also
https://url.spec.whatwg.org/#dom-url-username
Definition at line 103 of file url-setters.cpp.
References ada::unicode::percent_encode(), and ada::character_sets::USERINFO_PERCENT_ENCODE.
to_string()
std::string ada::url::to_string () const override virtual
Returns a JSON string representation of this URL.
Implements ada::url_base.
Definition at line 532 of file url.cpp.
References get_protocol(), has_credentials(), ada::url_base::has_opaque_path, has_search(), and ada::url_base::is_valid.
Referenced by ada::operator<<().
Friends And Related Symbol Documentation
ada::helpers::strip_trailing_spaces_from_opaque_path
void ada::helpers::strip_trailing_spaces_from_opaque_path (ada::url & url) friend
ada::parser::parse_url [1/2]
ada::url ada::parser::parse_url (std::string_view , const ada::url *) friend
ada::parser::parse_url [2/2]
ada::url_aggregator ada::parser::parse_url (std::string_view , const ada::url_aggregator *) friend
The documentation for this struct was generated from the following files:
include/ada/url.h
include/ada/url-inl.h
src/url-getters.cpp
src/url-setters.cpp
src/url.cpp