Ada: ada::scheme Namespace Reference
ada::scheme Namespace Reference
Includes the scheme declarations.
Namespaces
details
Includes the definitions for scheme specific entities.
Enumerations
enum type {
HTTP = 0 , NOT_SPECIAL = 1 , HTTPS = 2 , WS = 3 ,
FTP = 4 , WSS = 5 , FILE = 6
}
Functions
constexpr ada_really_inline bool is_special (std::string_view scheme)
constexpr uint16_t get_special_port (std::string_view scheme) noexcept
constexpr uint16_t get_special_port (ada::scheme::type type) noexcept
constexpr ada::scheme::type get_scheme_type (std::string_view scheme) noexcept
Detailed Description
Includes the scheme declarations.
Enumeration Type Documentation
type
enum ada::scheme::type
Type of the scheme as an enum. Using strings to represent a scheme type is not ideal because checking for types involves string comparisons. It is faster to use a simple integer.
Enumerator
HTTP
NOT_SPECIAL
HTTPS
WS
FTP
WSS
FILE
Definition at line 26 of file scheme.h.
Function Documentation
get_scheme_type()
constexpr ada::scheme::type ada::scheme::get_scheme_type (std::string_view scheme) constexpr noexcept
Returns the scheme of an input, or NOT_SPECIAL if it's not a special scheme defined by the spec.
Definition at line 42 of file scheme-inl.h.
References ada::scheme::details::is_special_list, and NOT_SPECIAL.
Referenced by ada::url::set_scheme().
get_special_port() [1/2]
constexpr uint16_t ada::scheme::get_special_port (ada::scheme::type type) constexpr noexcept
Returns the port number of a special scheme.
See also
https://url.spec.whatwg.org/#special-scheme
Definition at line 39 of file scheme-inl.h.
References ada::scheme::details::special_ports.
get_special_port() [2/2]
constexpr uint16_t ada::scheme::get_special_port (std::string_view scheme) constexpr noexcept
A special scheme is an ASCII string that is listed in the first column of the following table. The default port for a special scheme is listed in the second column on the same row. The default port for any other ASCII string is null.
See also
https://url.spec.whatwg.org/#url-miscellaneous
Parameters
scheme
Returns
The special port
Definition at line 31 of file scheme-inl.h.
References ada::scheme::details::is_special_list, and ada::scheme::details::special_ports.
is_special()
constexpr ada_really_inline bool ada::scheme::is_special (std::string_view scheme) constexpr
A special scheme is an ASCII string that is listed in the first column of the following table. The default port for a special scheme is listed in the second column on the same row. The default port for any other ASCII string is null.
See also
https://url.spec.whatwg.org/#url-miscellaneous
Parameters
scheme
Returns
If scheme is a special scheme
Definition at line 25 of file scheme-inl.h.
References ada::scheme::details::is_special_list.
Referenced by ada::helpers::get_host_delimiter_location(), and ada::url::set_scheme().