Ada: tl::detail Namespace Reference
tl::detail Namespace Reference
Namespaces
swap_adl_tests
Classes
struct conjunction
struct conjunction< B >
struct conjunction< B, Bs... >
struct invoke_result_impl
struct invoke_result_impl< F, decltype(detail::invoke(std::declval< F >(), std::declval< Us >()...), void()), Us... >
struct is_swappable
struct is_swappable< T[N], T[N]>
struct is_nothrow_swappable
struct is_expected_impl
struct is_expected_impl< expected< T, E > >
struct no_init_t
struct expected_storage_base
struct expected_storage_base< T, E, true, true >
struct expected_storage_base< T, E, true, false >
struct expected_storage_base< T, E, false, true >
struct expected_storage_base< void, E, false, true >
struct expected_storage_base< void, E, false, false >
struct expected_operations_base
struct expected_operations_base< void, E >
struct expected_copy_base
struct expected_copy_base< T, E, false >
struct expected_move_base
struct expected_move_base< T, E, false >
struct expected_copy_assign_base
struct expected_copy_assign_base< T, E, false >
struct expected_move_assign_base
struct expected_move_assign_base< T, E, false >
struct expected_delete_ctor_base
struct expected_delete_ctor_base< T, E, true, false >
struct expected_delete_ctor_base< T, E, false, true >
struct expected_delete_ctor_base< T, E, false, false >
struct expected_delete_assign_base
struct expected_delete_assign_base< T, E, true, false >
struct expected_delete_assign_base< T, E, false, true >
struct expected_delete_assign_base< T, E, false, false >
struct default_constructor_tag
struct expected_default_ctor_base
struct expected_default_ctor_base< T, E, false >
struct TC
Typedefs
template<class T >
using remove_const_t = typename std::remove_const< T >::type
template<class T >
using remove_reference_t = typename std::remove_reference< T >::type
template<class T >
using decay_t = typename std::decay< T >::type
template<bool E, class T = void>
using enable_if_t = typename std::enable_if< E, T >::type
template<bool B, class T , class F >
using conditional_t = typename std::conditional< B, T, F >::type
template<class F , class... Us>
using invoke_result = invoke_result_impl< F, void, Us... >
template<class F , class... Us>
using invoke_result_t = typename invoke_result< F, Us... >::type
template<class T >
using is_expected = is_expected_impl< decay_t< T > >
template<class T , class E , class U >
using expected_enable_forward_value = detail::enable_if_t< std::is_constructible< T, U && >::value &&!std::is_same< detail::decay_t< U >, in_place_t >::value &&!std::is_same< expected< T, E >, detail::decay_t< U > >::value &&!std::is_same< unexpected< E >, detail::decay_t< U > >::value >
template<class T , class E , class U , class G , class UR , class GR >
using expected_enable_from_other = detail::enable_if_t< std::is_constructible< T, UR >::value &&std::is_constructible< E, GR >::value &&!std::is_constructible< T, expected< U, G > & >::value &&!std::is_constructible< T, expected< U, G > && >::value &&!std::is_constructible< T, const expected< U, G > & >::value &&!std::is_constructible< T, const expected< U, G > && >::value &&!std::is_convertible< expected< U, G > &, T >::value &&!std::is_convertible< expected< U, G > &&, T >::value &&!std::is_convertible< const expected< U, G > &, T >::value &&!std::is_convertible< const expected< U, G > &&, T >::value >
template<class T , class U >
using is_void_or = conditional_t< std::is_void< T >::value, std::true_type, U >
template<class T >
using is_copy_constructible_or_void = is_void_or< T, std::is_copy_constructible< T > >
template<class T >
using is_move_constructible_or_void = is_void_or< T, std::is_move_constructible< T > >
template<class T >
using is_copy_assignable_or_void = is_void_or< T, std::is_copy_assignable< T > >
template<class T >
using is_move_assignable_or_void = is_void_or< T, std::is_move_assignable< T > >
template<class Exp >
using exp_t = typename detail::decay_t< Exp >::value_type
template<class Exp >
using err_t = typename detail::decay_t< Exp >::error_type
template<class Exp , class Ret >
using ret_t = expected< Ret, err_t< Exp > >
Functions
template<typename E >
TL_EXPECTED_11_CONSTEXPR void throw_exception (E &&e)
template<typename Fn , typename... Args, typename = enable_if_t<std::is_member_pointer<decay_t<Fn>>::value>, int = 0>
constexpr auto invoke (Fn &&f, Args &&...args) noexcept(noexcept(std::mem_fn(f)(std::forward< Args >(args)...))) -> decltype(std::mem_fn(f)(std::forward< Args >(args)...))
template<typename Fn , typename... Args, typename = enable_if_t<!std::is_member_pointer<decay_t<Fn>>::value>>
constexpr auto invoke (Fn &&f, Args &&...args) noexcept(noexcept(std::forward< Fn >(f)(std::forward< Args >(args)...))) -> decltype(std::forward< Fn >(f)(std::forward< Args >(args)...))
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr>
auto and_then_impl (Exp &&exp, F &&f) -> Ret
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>())), detail::enable_if_t< std::is_void< exp_t< Exp >>::value > * = nullptr>
constexpr auto and_then_impl (Exp &&exp, F &&f) -> Ret
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr>
constexpr auto expected_map_impl (Exp &&exp, F &&f) -> ret_t< Exp, detail::decay_t< Ret >>
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr>
auto expected_map_impl (Exp &&exp, F &&f) -> expected< void, err_t< Exp >>
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr>
constexpr auto map_error_impl (Exp &&exp, F &&f) -> expected< exp_t< Exp >, detail::decay_t< Ret >>
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr>
auto map_error_impl (Exp &&exp, F &&f) -> expected< exp_t< Exp >, monostate >
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr>
auto or_else_impl (Exp &&exp, F &&f) -> Ret
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr>
detail::decay_t< Exp > or_else_impl (Exp &&exp, F &&f)
Variables
static constexpr no_init_t no_init {}
Typedef Documentation
conditional_t
template<bool B, class T , class F > using tl::detail::conditional_t = typedef typename std::conditional<B, T, F>::type
Definition at line 224 of file expected.h.
decay_t
template<class T > using tl::detail::decay_t = typedef typename std::decay<T>::type
Definition at line 220 of file expected.h.
enable_if_t
template<bool E, class T = void> using tl::detail::enable_if_t = typedef typename std::enable_if<E, T>::type
Definition at line 222 of file expected.h.
err_t
template<class Exp > using tl::detail::err_t = typedef typename detail::decay_t<Exp>::error_type
Definition at line 1970 of file expected.h.
exp_t
template<class Exp > using tl::detail::exp_t = typedef typename detail::decay_t<Exp>::value_type
Definition at line 1969 of file expected.h.
expected_enable_forward_value
template<class T , class E , class U > using tl::detail::expected_enable_forward_value = typedef detail::enable_if_t< std::is_constructible<T, U &&>::value && !std::is_same<detail::decay_t<U>, in_place_t>::value && !std::is_same<expected<T, E>, detail::decay_t<U> >::value && !std::is_same<unexpected<E>, detail::decay_t<U> >::value>
Definition at line 387 of file expected.h.
expected_enable_from_other
template<class T , class E , class U , class G , class UR , class GR > using tl::detail::expected_enable_from_other = typedef detail::enable_if_t< std::is_constructible<T, UR>::value && std::is_constructible<E, GR>::value && !std::is_constructible<T, expected<U, G> &>::value && !std::is_constructible<T, expected<U, G> &&>::value && !std::is_constructible<T, const expected<U, G> &>::value && !std::is_constructible<T, const expected<U, G> &&>::value && !std::is_convertible<expected<U, G> &, T>::value && !std::is_convertible<expected<U, G> &&, T>::value && !std::is_convertible<const expected<U, G> &, T>::value && !std::is_convertible<const expected<U, G> &&, T>::value>
Definition at line 394 of file expected.h.
invoke_result
template<class F , class... Us> using tl::detail::invoke_result = typedef invoke_result_impl<F, void, Us...>
Definition at line 303 of file expected.h.
invoke_result_t
template<class F , class... Us> using tl::detail::invoke_result_t = typedef typename invoke_result<F, Us...>::type
Definition at line 306 of file expected.h.
is_copy_assignable_or_void
template<class T > using tl::detail::is_copy_assignable_or_void = typedef is_void_or<T, std::is_copy_assignable<T> >
Definition at line 418 of file expected.h.
is_copy_constructible_or_void
template<class T > using tl::detail::is_copy_constructible_or_void = typedef is_void_or<T, std::is_copy_constructible<T> >
Definition at line 410 of file expected.h.
is_expected
template<class T > using tl::detail::is_expected = typedef is_expected_impl<decay_t<T> >
Definition at line 384 of file expected.h.
is_move_assignable_or_void
template<class T > using tl::detail::is_move_assignable_or_void = typedef is_void_or<T, std::is_move_assignable<T> >
Definition at line 421 of file expected.h.
is_move_constructible_or_void
template<class T > using tl::detail::is_move_constructible_or_void = typedef is_void_or<T, std::is_move_constructible<T> >
Definition at line 414 of file expected.h.
is_void_or
template<class T , class U > using tl::detail::is_void_or = typedef conditional_t<std::is_void<T>::value, std::true_type, U>
Definition at line 407 of file expected.h.
remove_const_t
template<class T > using tl::detail::remove_const_t = typedef typename std::remove_const<T>::type
Definition at line 217 of file expected.h.
remove_reference_t
template<class T > using tl::detail::remove_reference_t = typedef typename std::remove_reference<T>::type
Definition at line 219 of file expected.h.
ret_t
template<class Exp , class Ret > using tl::detail::ret_t = typedef expected<Ret, err_t<Exp> >
Definition at line 1971 of file expected.h.
Function Documentation
and_then_impl() [1/2]
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr> auto tl::detail::and_then_impl (Exp && exp, F && f) -> Ret
Definition at line 2001 of file expected.h.
References invoke(), and tl::unexpect.
Referenced by tl::expected< T, E >::and_then().
and_then_impl() [2/2]
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>())), detail::enable_if_t< std::is_void< exp_t< Exp >>::value > * = nullptr> constexpr auto tl::detail::and_then_impl (Exp && exp, F && f) -> Ret constexpr
Definition at line 2012 of file expected.h.
References invoke(), and tl::unexpect.
expected_map_impl() [1/2]
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr> auto tl::detail::expected_map_impl (Exp && exp, F && f) -> expected<void, err_t<Exp>>
Definition at line 2093 of file expected.h.
References invoke().
expected_map_impl() [2/2]
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), *std::declval<Exp>())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr> constexpr auto tl::detail::expected_map_impl (Exp && exp, F && f) -> ret_t<Exp, detail::decay_t<Ret>> constexpr
Definition at line 2078 of file expected.h.
References tl::expected< T, E >::has_value(), invoke(), and tl::unexpect.
Referenced by tl::expected< T, E >::map(), and tl::expected< T, E >::transform().
invoke() [1/2]
template<typename Fn , typename... Args, typename = enable_if_t<!std::is_member_pointer<decay_t<Fn>>::value>> constexpr auto tl::detail::invoke (Fn && f, Args &&... args) -> decltype(std::forward<Fn>(f)(std::forward<Args>(args)...)) constexpr noexcept
Definition at line 284 of file expected.h.
invoke() [2/2]
template<typename Fn , typename... Args, typename = enable_if_t<std::is_member_pointer<decay_t<Fn>>::value>, int = 0> constexpr auto tl::detail::invoke (Fn && f, Args &&... args) -> decltype(std::mem_fn(f)(std::forward<Args>(args)...)) constexpr noexcept
Definition at line 276 of file expected.h.
Referenced by and_then_impl(), expected_map_impl(), map_error_impl(), and or_else_impl().
map_error_impl() [1/2]
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr> constexpr auto tl::detail::map_error_impl (Exp && exp, F && f) -> expected<exp_t<Exp>, detail::decay_t<Ret>> constexpr
Definition at line 2190 of file expected.h.
References tl::expected< T, E >::has_value(), invoke(), and tl::unexpect.
map_error_impl() [2/2]
template<class Exp , class F , detail::enable_if_t<!std::is_void< exp_t< Exp >>::value > * = nullptr, class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr> auto tl::detail::map_error_impl (Exp && exp, F && f) -> expected<exp_t<Exp>, monostate>
Definition at line 2205 of file expected.h.
References invoke(), and tl::unexpect.
or_else_impl() [1/2]
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t< std::is_void< Ret >::value > * = nullptr> detail::decay_t<Exp> tl::detail::or_else_impl (Exp && exp, F && f)
Definition at line 2284 of file expected.h.
References invoke().
or_else_impl() [2/2]
template<class Exp , class F , class Ret = decltype(detail::invoke(std::declval<F>(), std::declval<Exp>().error())), detail::enable_if_t<!std::is_void< Ret >::value > * = nullptr> auto tl::detail::or_else_impl (Exp && exp, F && f) -> Ret
Definition at line 2273 of file expected.h.
References invoke().
Referenced by tl::expected< T, E >::or_else().
throw_exception()
template<typename E > TL_EXPECTED_11_CONSTEXPR void tl::detail::throw_exception (E && e)
Definition at line 202 of file expected.h.
Referenced by tl::expected< T, E >::value().
Variable Documentation
no_init
constexpr no_init_t tl::detail::no_init {} static constexpr
Definition at line 427 of file expected.h.