#!/usr/bin/env bash
# Run clang-format and clang-tidy on all tracked source files.
# Uses the locally installed LLVM 22 toolchain when available,
# falling back to the xianpengshen/clang-tools:22 Docker image.
#
# The Docker fallback installs cmake inside the container on-the-fly and
# runs the full cmake + CMAKE_CXX_CLANG_TIDY pipeline with clang++-22,
# exactly mirroring what CI does.  This avoids the false-positive warnings
# that would arise from a compile_commands.json generated by GCC (which
# injects GCC-specific flags that clang-tidy cannot parse).
#
# Usage: tools/run-clangcldocker.sh [extra clang-format flags...]
set -e

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
MAINSOURCE="$SCRIPTPATH/.."
DOCKER_IMAGE=xianpengshen/clang-tools:22

ALL_ADA_FILES=$(cd "$MAINSOURCE" && \
  git ls-tree --full-tree --name-only -r HEAD | grep -E '.*\.(c|h|cc|cpp|hh)$')

# ── helpers ──────────────────────────────────────────────────────────────────

have_tool_version() {
  # Returns 0 if $1 exists and reports "version 22." in its --version output.
  command -v "$1" >/dev/null 2>&1 && \
    "$1" --version 2>/dev/null | grep -qF 'version 22.'
}

require_docker() {
  command -v docker >/dev/null 2>&1 || {
    echo >&2 "docker not found. Install docker or the LLVM 22 toolchain."
    exit 1
  }
  docker info >/dev/null 2>&1 || {
    echo >&2 "Docker daemon is not running (try: docker info)."
    exit 1
  }
  docker pull -q "$DOCKER_IMAGE" >/dev/null
}

docker_run() {
  local it_flag=""
  [ -t 0 ] && it_flag="-it"
  # shellcheck disable=SC2086
  docker run --rm $it_flag \
    -v "$MAINSOURCE":"$MAINSOURCE":Z \
    -w "$MAINSOURCE" \
    -u "$(id -u):$(id -g)" \
    "$DOCKER_IMAGE" "$@"
}

# Number of parallel jobs, with a sane fallback.
JOBS=$(nproc 2>/dev/null || sysctl -n hw.logicalcpu 2>/dev/null || echo 4)

# ── clang-format ─────────────────────────────────────────────────────────────
echo "=== clang-format ==="

# shellcheck disable=SC2086
if have_tool_version clang-format-22; then
  cd "$MAINSOURCE"
  clang-format-22 --style=file --verbose -i "$@" $ALL_ADA_FILES
elif have_tool_version clang-format; then
  cd "$MAINSOURCE"
  clang-format --style=file --verbose -i "$@" $ALL_ADA_FILES
else
  echo "clang-format 22 not found locally — using docker"
  require_docker
  # shellcheck disable=SC2086
  docker_run clang-format --style=file --verbose -i "$@" $ALL_ADA_FILES
fi

# ── clang-tidy ────────────────────────────────────────────────────────────────
echo "=== clang-tidy ==="

# Run cmake with CMAKE_CXX_CLANG_TIDY so that clang-tidy is invoked on every
# translation unit during the build, using clang++-22 and -stdlib=libc++.
# This is identical to what CI does and ensures there are no GCC-specific
# flags in the compilation database that would cause false positives.
run_tidy_cmake() {
  local tidy="$1" cxx="$2"
  cd "$MAINSOURCE"
  CXX="$cxx" cmake -B build-clang-tidy \
    -DADA_TESTING=ON \
    -DADA_USE_UNSAFE_STD_REGEX_PROVIDER=ON \
    -DCMAKE_CXX_CLANG_TIDY="$tidy" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_CXX_FLAGS="-stdlib=libc++"
  cmake --build build-clang-tidy -j"$JOBS"
}

if have_tool_version clang-tidy-22 && command -v clang++-22 >/dev/null 2>&1; then
  run_tidy_cmake clang-tidy-22 clang++-22
elif have_tool_version clang-tidy && command -v clang++ >/dev/null 2>&1; then
  run_tidy_cmake clang-tidy clang++
else
  echo "clang-tidy 22 not found locally — using docker"
  require_docker
  # The Docker image has clang++-22 and clang-tidy-22 but not cmake.
  # Install cmake inside the container and run the full cmake+tidy pipeline
  # with clang++-22, exactly mirroring CI.  The source tree is mounted at
  # the same absolute path so all relative paths resolve correctly.
  docker run --rm \
    -v "$MAINSOURCE":"$MAINSOURCE":Z \
    -w "$MAINSOURCE" \
    -e DEBIAN_FRONTEND=noninteractive \
    -e CPM_SOURCE_CACHE="$MAINSOURCE/.cpm-cache" \
    --entrypoint bash \
    "$DOCKER_IMAGE" -c "
      apt-get update -qq >/dev/null 2>&1 &&
      apt-get install -y -qq --no-install-recommends \
        ca-certificates cmake ninja-build git clang-22 \
        libc++-22-dev libc++abi-22-dev >/dev/null 2>&1 &&
      rm -rf build-clang-tidy &&
      CC=clang-22 CXX=clang++-22 cmake -B build-clang-tidy -G Ninja \
        -DADA_TESTING=ON \
        -DADA_USE_UNSAFE_STD_REGEX_PROVIDER=ON \
        -DCMAKE_CXX_CLANG_TIDY=clang-tidy-22 \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_CXX_FLAGS='-stdlib=libc++' \
        -DCPM_SOURCE_CACHE=\"$MAINSOURCE/.cpm-cache\" &&
      cmake --build build-clang-tidy -j\$(nproc)
    "
fi
