Ada: singleheader/demo.cpp File Reference
demo.cpp File Reference
#include "ada.cpp"
#include "ada.h"
#include <iostream>
Functions
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 5 of file demo.cpp.
References ada::url::get_host(), ada::url::get_protocol(), ada::parse(), and ada::url::set_protocol().