Ada: tl::expected< T, E > Class Template Reference
tl::expected< T, E > Class Template Reference
#include <expected.h>
Public Types
typedef T value_type
typedef E error_type
typedef unexpected< E > unexpected_type
Public Member Functions
template<class F >
TL_EXPECTED_11_CONSTEXPR auto and_then (F &&f) &-> decltype(and_then_impl(std::declval< expected & >(), std::forward< F >(f)))
template<class F >
TL_EXPECTED_11_CONSTEXPR auto and_then (F &&f) &&-> decltype(and_then_impl(std::declval< expected && >(), std::forward< F >(f)))
template<class F >
constexpr auto and_then (F &&f) const &-> decltype(and_then_impl(std::declval< expected const & >(), std::forward< F >(f)))
template<class F >
constexpr auto and_then (F &&f) const &&-> decltype(and_then_impl(std::declval< expected const && >(), std::forward< F >(f)))
template<class F >
decltype(expected_map_impl(std::declval< expected >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR map (F &&f) &&
template<class F >
decltype(expected_map_impl(std::declval< expected >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR transform (F &&f) &&
template<class F >
expected TL_EXPECTED_11_CONSTEXPR or_else (F &&f) &
template<class F >
expected TL_EXPECTED_11_CONSTEXPR or_else (F &&f) &&
template<class F >
constexpr expected or_else (F &&f) const &
template<class F >
constexpr expected or_else (F &&f) const &&
constexpr expected ()=default
constexpr expected (const expected &rhs)=default
constexpr expected (expected &&rhs)=default
expected & operator= (const expected &rhs)=default
expected & operator= (expected &&rhs)=default
template<class... Args, detail::enable_if_t< std::is_constructible< T, Args &&... >::value > * = nullptr>
constexpr expected (in_place_t, Args &&...args)
template<class U , class... Args, detail::enable_if_t< std::is_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr>
constexpr expected (in_place_t, std::initializer_list< U > il, Args &&...args)
template<class G = E, detail::enable_if_t< std::is_constructible< E, const G & >::value > * = nullptr, detail::enable_if_t<!std::is_convertible< const G &, E >::value > * = nullptr>
constexpr expected (const unexpected< G > &e)
template<class G = E, detail::enable_if_t< std::is_constructible< E, const G & >::value > * = nullptr, detail::enable_if_t< std::is_convertible< const G &, E >::value > * = nullptr>
constexpr expected (unexpected< G > const &e)
template<class G = E, detail::enable_if_t< std::is_constructible< E, G && >::value > * = nullptr, detail::enable_if_t<!std::is_convertible< G &&, E >::value > * = nullptr>
constexpr expected (unexpected< G > &&e) noexcept(std::is_nothrow_constructible< E, G && >::value)
template<class G = E, detail::enable_if_t< std::is_constructible< E, G && >::value > * = nullptr, detail::enable_if_t< std::is_convertible< G &&, E >::value > * = nullptr>
constexpr expected (unexpected< G > &&e) noexcept(std::is_nothrow_constructible< E, G && >::value)
template<class... Args, detail::enable_if_t< std::is_constructible< E, Args &&... >::value > * = nullptr>
constexpr expected (unexpect_t, Args &&...args)
template<class U , class... Args, detail::enable_if_t< std::is_constructible< E, std::initializer_list< U > &, Args &&... >::value > * = nullptr>
constexpr expected (unexpect_t, std::initializer_list< U > il, Args &&...args)
template<class U , class G , detail::enable_if_t<!(std::is_convertible< U const &, T >::value &&std::is_convertible< G const &, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, const U &, const G & > * = nullptr>
TL_EXPECTED_11_CONSTEXPR expected (const expected< U, G > &rhs)
template<class U , class G , detail::enable_if_t<(std::is_convertible< U const &, T >::value &&std::is_convertible< G const &, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, const U &, const G & > * = nullptr>
TL_EXPECTED_11_CONSTEXPR expected (const expected< U, G > &rhs)
template<class U , class G , detail::enable_if_t<!(std::is_convertible< U &&, T >::value &&std::is_convertible< G &&, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, U &&, G && > * = nullptr>
TL_EXPECTED_11_CONSTEXPR expected (expected< U, G > &&rhs)
template<class U , class G , detail::enable_if_t<(std::is_convertible< U &&, T >::value &&std::is_convertible< G &&, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, U &&, G && > * = nullptr>
TL_EXPECTED_11_CONSTEXPR expected (expected< U, G > &&rhs)
template<class U = T, detail::enable_if_t<!std::is_convertible< U &&, T >::value > * = nullptr, detail::expected_enable_forward_value< T, E, U > * = nullptr>
TL_EXPECTED_MSVC2015_CONSTEXPR expected (U &&v)
template<class U = T, detail::enable_if_t< std::is_convertible< U &&, T >::value > * = nullptr, detail::expected_enable_forward_value< T, E, U > * = nullptr>
TL_EXPECTED_MSVC2015_CONSTEXPR expected (U &&v)
template<class U = T, class G = T, detail::enable_if_t< std::is_nothrow_constructible< T, U && >::value > * = nullptr, detail::enable_if_t<!std::is_void< G >::value > * = nullptr, detail::enable_if_t<(!std::is_same< expected< T, E >, detail::decay_t< U >>::value &&!detail::conjunction< std::is_scalar< T >, std::is_same< T, detail::decay_t< U >>>::value &&std::is_constructible< T, U >::value &&std::is_assignable< G &, U >::value &&std::is_nothrow_move_constructible< E >::value)> * = nullptr>
expected & operator= (U &&v)
template<class U = T, class G = T, detail::enable_if_t<!std::is_nothrow_constructible< T, U && >::value > * = nullptr, detail::enable_if_t<!std::is_void< U >::value > * = nullptr, detail::enable_if_t<(!std::is_same< expected< T, E >, detail::decay_t< U >>::value &&!detail::conjunction< std::is_scalar< T >, std::is_same< T, detail::decay_t< U >>>::value &&std::is_constructible< T, U >::value &&std::is_assignable< G &, U >::value &&std::is_nothrow_move_constructible< E >::value)> * = nullptr>
expected & operator= (U &&v)
template<class G = E, detail::enable_if_t< std::is_nothrow_copy_constructible< G >::value &&std::is_assignable< G &, G >::value > * = nullptr>
expected & operator= (const unexpected< G > &rhs)
template<class G = E, detail::enable_if_t< std::is_nothrow_move_constructible< G >::value &&std::is_move_assignable< G >::value > * = nullptr>
expected & operator= (unexpected< G > &&rhs) noexcept
template<class... Args, detail::enable_if_t< std::is_nothrow_constructible< T, Args &&... >::value > * = nullptr>
void emplace (Args &&...args)
template<class... Args, detail::enable_if_t<!std::is_nothrow_constructible< T, Args &&... >::value > * = nullptr>
void emplace (Args &&...args)
template<class U , class... Args, detail::enable_if_t< std::is_nothrow_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr>
void emplace (std::initializer_list< U > il, Args &&...args)
template<class U , class... Args, detail::enable_if_t<!std::is_nothrow_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr>
void emplace (std::initializer_list< U > il, Args &&...args)
template<class OT = T, class OE = E>
detail::enable_if_t< detail::is_swappable< OT >::value &&detail::is_swappable< OE >::value &&(std::is_nothrow_move_constructible< OT >::value||std::is_nothrow_move_constructible< OE >::value)> swap (expected &rhs) noexcept(std::is_nothrow_move_constructible< T >::value &&detail::is_nothrow_swappable< T >::value &&std::is_nothrow_move_constructible< E >::value &&detail::is_nothrow_swappable< E >::value)
constexpr const T * operator-> () const
TL_EXPECTED_11_CONSTEXPR T * operator-> ()
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
constexpr const U & operator* () const &
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR U & operator* () &
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
constexpr const U && operator* () const &&
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR U && operator* () &&
constexpr bool has_value () const noexcept
constexpr operator bool () const noexcept
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR const U & value () const &
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR U & value () &
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR const U && value () const &&
template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr>
TL_EXPECTED_11_CONSTEXPR U && value () &&
constexpr const E & error () const &
TL_EXPECTED_11_CONSTEXPR E & error () &
constexpr const E && error () const &&
TL_EXPECTED_11_CONSTEXPR E && error () &&
template<class U >
constexpr T value_or (U &&v) const &
template<class U >
TL_EXPECTED_11_CONSTEXPR T value_or (U &&v) &&
Public Attributes
template<class F >
decltype(expected_map_impl(std::declval< expected & >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR map (F &&f) &
template<class F >
constexpr decltype(expected_map_impl(std::declval< const expected & >(), std::declval< F && >())) map (F &&f) const &
template<class F >
constexpr decltype(expected_map_impl(std::declval< const expected && >(), std::declval< F && >())) map (F &&f) const &&
template<class F >
decltype(expected_map_impl(std::declval< expected & >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR transform (F &&f) &
template<class F >
constexpr decltype(expected_map_impl(std::declval< const expected & >(), std::declval< F && >())) transform (F &&f) const &
template<class F >
constexpr decltype(expected_map_impl(std::declval< const expected && >(), std::declval< F && >())) transform (F &&f) const &&
template<class F >
decltype(map_error_impl(std::declval< expected & >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR map_error (F &&f) &
template<class F >
decltype(map_error_impl(std::declval< expected && >(), std::declval< F && >())) TL_EXPECTED_11_CONSTEXPR map_error (F &&f) &&
template<class F >
constexpr decltype(map_error_impl(std::declval< const expected & >(), std::declval< F && >())) map_error (F &&f) const &
template<class F >
constexpr decltype(map_error_impl(std::declval< const expected && >(), std::declval< F && >())) map_error (F &&f) const &&
Detailed Description
template<class T, class E>
class tl::expected< T, E >
An expected<T, E> object is an object that contains the storage for another object and manages the lifetime of this contained object T. Alternatively it could contain the storage for another unexpected object E. The contained object may not be initialized after the expected object has been initialized, and may not be destroyed before the expected object has been destroyed. The initialization state of the contained object is tracked by the expected object.
Examples
/home/runner/work/ada/ada/include/ada/implementation.h.
Definition at line 1236 of file expected.h.
Member Typedef Documentation
error_type
template<class T , class E > typedef E tl::expected< T, E >::error_type
Definition at line 1276 of file expected.h.
unexpected_type
template<class T , class E > typedef unexpected<E> tl::expected< T, E >::unexpected_type
Definition at line 1277 of file expected.h.
value_type
template<class T , class E > typedef T tl::expected< T, E >::value_type
Definition at line 1275 of file expected.h.
Constructor & Destructor Documentation
expected() [1/17]
template<class T , class E > constexpr tl::expected< T, E >::expected () constexpr default
expected() [2/17]
template<class T , class E > constexpr tl::expected< T, E >::expected (const expected< T, E > & rhs) constexpr default
expected() [3/17]
template<class T , class E > constexpr tl::expected< T, E >::expected (expected< T, E > && rhs) constexpr default
expected() [4/17]
template<class T , class E > template<class... Args, detail::enable_if_t< std::is_constructible< T, Args &&... >::value > * = nullptr> constexpr tl::expected< T, E >::expected (in_place_t , Args &&... args) inline constexpr
Definition at line 1482 of file expected.h.
expected() [5/17]
template<class T , class E > template<class U , class... Args, detail::enable_if_t< std::is_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr> constexpr tl::expected< T, E >::expected (in_place_t , std::initializer_list< U > il, Args &&... args) inline constexpr
Definition at line 1489 of file expected.h.
expected() [6/17]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_constructible< E, const G & >::value > * = nullptr, detail::enable_if_t<!std::is_convertible< const G &, E >::value > * = nullptr> constexpr tl::expected< T, E >::expected (const unexpected< G > & e) inline explicit constexpr
Definition at line 1498 of file expected.h.
expected() [7/17]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_constructible< E, const G & >::value > * = nullptr, detail::enable_if_t< std::is_convertible< const G &, E >::value > * = nullptr> constexpr tl::expected< T, E >::expected (unexpected< G > const & e) inline constexpr
Definition at line 1507 of file expected.h.
expected() [8/17]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_constructible< E, G && >::value > * = nullptr, detail::enable_if_t<!std::is_convertible< G &&, E >::value > * = nullptr> constexpr tl::expected< T, E >::expected (unexpected< G > && e) inline explicit constexpr noexcept
Definition at line 1515 of file expected.h.
expected() [9/17]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_constructible< E, G && >::value > * = nullptr, detail::enable_if_t< std::is_convertible< G &&, E >::value > * = nullptr> constexpr tl::expected< T, E >::expected (unexpected< G > && e) inline constexpr noexcept
Definition at line 1524 of file expected.h.
expected() [10/17]
template<class T , class E > template<class... Args, detail::enable_if_t< std::is_constructible< E, Args &&... >::value > * = nullptr> constexpr tl::expected< T, E >::expected (unexpect_t , Args &&... args) inline explicit constexpr
Definition at line 1532 of file expected.h.
expected() [11/17]
template<class T , class E > template<class U , class... Args, detail::enable_if_t< std::is_constructible< E, std::initializer_list< U > &, Args &&... >::value > * = nullptr> constexpr tl::expected< T, E >::expected (unexpect_t , std::initializer_list< U > il, Args &&... args) inline explicit constexpr
Definition at line 1539 of file expected.h.
expected() [12/17]
template<class T , class E > template<class U , class G , detail::enable_if_t<!(std::is_convertible< U const &, T >::value &&std::is_convertible< G const &, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, const U &, const G & > * = nullptr> TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::expected (const expected< U, G > & rhs) inline explicit
Definition at line 1550 of file expected.h.
expected() [13/17]
template<class T , class E > template<class U , class G , detail::enable_if_t<(std::is_convertible< U const &, T >::value &&std::is_convertible< G const &, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, const U &, const G & > * = nullptr> TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::expected (const expected< U, G > & rhs) inline
Definition at line 1565 of file expected.h.
expected() [14/17]
template<class T , class E > template<class U , class G , detail::enable_if_t<!(std::is_convertible< U &&, T >::value &&std::is_convertible< G &&, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, U &&, G && > * = nullptr> TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::expected (expected< U, G > && rhs) inline explicit
Definition at line 1579 of file expected.h.
expected() [15/17]
template<class T , class E > template<class U , class G , detail::enable_if_t<(std::is_convertible< U &&, T >::value &&std::is_convertible< G &&, E >::value)> * = nullptr, detail::expected_enable_from_other< T, E, U, G, U &&, G && > * = nullptr> TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::expected (expected< U, G > && rhs) inline
Definition at line 1593 of file expected.h.
expected() [16/17]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_convertible< U &&, T >::value > * = nullptr, detail::expected_enable_forward_value< T, E, U > * = nullptr> TL_EXPECTED_MSVC2015_CONSTEXPR tl::expected< T, E >::expected (U && v) inline explicit
Definition at line 1606 of file expected.h.
expected() [17/17]
template<class T , class E > template<class U = T, detail::enable_if_t< std::is_convertible< U &&, T >::value > * = nullptr, detail::expected_enable_forward_value< T, E, U > * = nullptr> TL_EXPECTED_MSVC2015_CONSTEXPR tl::expected< T, E >::expected (U && v) inline
Definition at line 1613 of file expected.h.
Member Function Documentation
and_then() [1/4]
template<class T , class E > template<class F > TL_EXPECTED_11_CONSTEXPR auto tl::expected< T, E >::and_then (F && f) && -> decltype(and_then_impl(std::declval<expected &&>(), std::forward<F>(f))) inline
Definition at line 1306 of file expected.h.
References tl::detail::and_then_impl().
and_then() [2/4]
template<class T , class E > template<class F > TL_EXPECTED_11_CONSTEXPR auto tl::expected< T, E >::and_then (F && f) & -> decltype(and_then_impl(std::declval<expected &>(), std::forward<F>(f))) inline
Definition at line 1300 of file expected.h.
References tl::detail::and_then_impl().
and_then() [3/4]
template<class T , class E > template<class F > constexpr auto tl::expected< T, E >::and_then (F && f) const && -> decltype(and_then_impl(std::declval<expected const &&>(), std::forward<F>(f))) inline constexpr
Definition at line 1318 of file expected.h.
References tl::detail::and_then_impl().
and_then() [4/4]
template<class T , class E > template<class F > constexpr auto tl::expected< T, E >::and_then (F && f) const & -> decltype(and_then_impl(std::declval<expected const &>(), std::forward<F>(f))) inline constexpr
Definition at line 1311 of file expected.h.
References tl::detail::and_then_impl().
emplace() [1/4]
template<class T , class E > template<class... Args, detail::enable_if_t< std::is_nothrow_constructible< T, Args &&... >::value > * = nullptr> void tl::expected< T, E >::emplace (Args &&... args) inline
Definition at line 1708 of file expected.h.
emplace() [2/4]
template<class T , class E > template<class... Args, detail::enable_if_t<!std::is_nothrow_constructible< T, Args &&... >::value > * = nullptr> void tl::expected< T, E >::emplace (Args &&... args) inline
Definition at line 1720 of file expected.h.
emplace() [3/4]
template<class T , class E > template<class U , class... Args, detail::enable_if_t< std::is_nothrow_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr> void tl::expected< T, E >::emplace (std::initializer_list< U > il, Args &&... args) inline
Definition at line 1746 of file expected.h.
emplace() [4/4]
template<class T , class E > template<class U , class... Args, detail::enable_if_t<!std::is_nothrow_constructible< T, std::initializer_list< U > &, Args &&... >::value > * = nullptr> void tl::expected< T, E >::emplace (std::initializer_list< U > il, Args &&... args) inline
Definition at line 1760 of file expected.h.
error() [1/4]
template<class T , class E > TL_EXPECTED_11_CONSTEXPR E& tl::expected< T, E >::error () & inline
Definition at line 1950 of file expected.h.
error() [2/4]
template<class T , class E > TL_EXPECTED_11_CONSTEXPR E&& tl::expected< T, E >::error () && inline
Definition at line 1952 of file expected.h.
error() [3/4]
template<class T , class E > constexpr const E& tl::expected< T, E >::error () const & inline constexpr
Definition at line 1949 of file expected.h.
Referenced by tl::operator!=(), and tl::operator==().
error() [4/4]
template<class T , class E > constexpr const E&& tl::expected< T, E >::error () const && inline constexpr
Definition at line 1951 of file expected.h.
has_value()
template<class T , class E > constexpr bool tl::expected< T, E >::has_value () const inline constexpr noexcept
Definition at line 1917 of file expected.h.
Referenced by tl::detail::expected_map_impl(), tl::detail::map_error_impl(), tl::operator!=(), tl::operator==(), ada::url::set_href(), and tl::expected< T, E >::swap().
map()
template<class T , class E > template<class F > decltype(expected_map_impl(std::declval<expected>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::map (F && f) && inline
Definition at line 1349 of file expected.h.
References tl::detail::expected_map_impl().
operator bool()
template<class T , class E > constexpr tl::expected< T, E >::operator bool () const inline explicit constexpr noexcept
Definition at line 1918 of file expected.h.
operator*() [1/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR U& tl::expected< T, E >::operator* () & inline
Definition at line 1903 of file expected.h.
operator*() [2/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR U&& tl::expected< T, E >::operator* () && inline
Definition at line 1913 of file expected.h.
operator*() [3/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> constexpr const U& tl::expected< T, E >::operator* () const & inline constexpr
Definition at line 1898 of file expected.h.
operator*() [4/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> constexpr const U&& tl::expected< T, E >::operator* () const && inline constexpr
Definition at line 1908 of file expected.h.
operator->() [1/2]
template<class T , class E > TL_EXPECTED_11_CONSTEXPR T* tl::expected< T, E >::operator-> () inline
Definition at line 1894 of file expected.h.
operator->() [2/2]
template<class T , class E > constexpr const T* tl::expected< T, E >::operator-> () const inline constexpr
Definition at line 1893 of file expected.h.
operator=() [1/6]
template<class T , class E > expected& tl::expected< T, E >::operator= (const expected< T, E > & rhs) default
operator=() [2/6]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_nothrow_copy_constructible< G >::value &&std::is_assignable< G &, G >::value > * = nullptr> expected& tl::expected< T, E >::operator= (const unexpected< G > & rhs) inline
Definition at line 1679 of file expected.h.
operator=() [3/6]
template<class T , class E > expected& tl::expected< T, E >::operator= (expected< T, E > && rhs) default
operator=() [4/6]
template<class T , class E > template<class U = T, class G = T, detail::enable_if_t< std::is_nothrow_constructible< T, U && >::value > * = nullptr, detail::enable_if_t<!std::is_void< G >::value > * = nullptr, detail::enable_if_t<(!std::is_same< expected< T, E >, detail::decay_t< U >>::value &&!detail::conjunction< std::is_scalar< T >, std::is_same< T, detail::decay_t< U >>>::value &&std::is_constructible< T, U >::value &&std::is_assignable< G &, U >::value &&std::is_nothrow_move_constructible< E >::value)> * = nullptr> expected& tl::expected< T, E >::operator= (U && v) inline
Definition at line 1628 of file expected.h.
operator=() [5/6]
template<class T , class E > template<class U = T, class G = T, detail::enable_if_t<!std::is_nothrow_constructible< T, U && >::value > * = nullptr, detail::enable_if_t<!std::is_void< U >::value > * = nullptr, detail::enable_if_t<(!std::is_same< expected< T, E >, detail::decay_t< U >>::value &&!detail::conjunction< std::is_scalar< T >, std::is_same< T, detail::decay_t< U >>>::value &&std::is_constructible< T, U >::value &&std::is_assignable< G &, U >::value &&std::is_nothrow_move_constructible< E >::value)> * = nullptr> expected& tl::expected< T, E >::operator= (U && v) inline
Definition at line 1652 of file expected.h.
operator=() [6/6]
template<class T , class E > template<class G = E, detail::enable_if_t< std::is_nothrow_move_constructible< G >::value &&std::is_move_assignable< G >::value > * = nullptr> expected& tl::expected< T, E >::operator= (unexpected< G > && rhs) inline noexcept
Definition at line 1694 of file expected.h.
or_else() [1/4]
template<class T , class E > template<class F > expected TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::or_else (F && f) & inline
Definition at line 1456 of file expected.h.
References tl::detail::or_else_impl().
or_else() [2/4]
template<class T , class E > template<class F > expected TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::or_else (F && f) && inline
Definition at line 1460 of file expected.h.
References tl::detail::or_else_impl().
or_else() [3/4]
template<class T , class E > template<class F > constexpr expected tl::expected< T, E >::or_else (F && f) const & inline constexpr
Definition at line 1464 of file expected.h.
References tl::detail::or_else_impl().
or_else() [4/4]
template<class T , class E > template<class F > constexpr expected tl::expected< T, E >::or_else (F && f) const && inline constexpr
Definition at line 1469 of file expected.h.
References tl::detail::or_else_impl().
swap()
template<class T , class E > template<class OT = T, class OE = E> detail::enable_if_t<detail::is_swappable<OT>::value && detail::is_swappable<OE>::value && (std::is_nothrow_move_constructible<OT>::value || std::is_nothrow_move_constructible<OE>::value)> tl::expected< T, E >::swap (expected< T, E > & rhs) inline noexcept
Definition at line 1876 of file expected.h.
References tl::expected< T, E >::has_value(), tl::expected< T, E >::swap(), and tl::swap().
Referenced by tl::expected< T, E >::swap(), and tl::swap().
transform()
template<class T , class E > template<class F > decltype(expected_map_impl(std::declval<expected>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::transform (F && f) && inline
Definition at line 1393 of file expected.h.
References tl::detail::expected_map_impl().
value() [1/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR U& tl::expected< T, E >::value () & inline
Definition at line 1929 of file expected.h.
References tl::detail::throw_exception().
value() [2/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR U&& tl::expected< T, E >::value () && inline
Definition at line 1943 of file expected.h.
References tl::detail::throw_exception().
value() [3/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR const U& tl::expected< T, E >::value () const & inline
Definition at line 1922 of file expected.h.
References tl::detail::throw_exception().
value() [4/4]
template<class T , class E > template<class U = T, detail::enable_if_t<!std::is_void< U >::value > * = nullptr> TL_EXPECTED_11_CONSTEXPR const U&& tl::expected< T, E >::value () const && inline
Definition at line 1936 of file expected.h.
References tl::detail::throw_exception().
value_or() [1/2]
template<class T , class E > template<class U > TL_EXPECTED_11_CONSTEXPR T tl::expected< T, E >::value_or (U && v) && inline
Definition at line 1960 of file expected.h.
value_or() [2/2]
template<class T , class E > template<class U > constexpr T tl::expected< T, E >::value_or (U && v) const & inline constexpr
Definition at line 1954 of file expected.h.
Member Data Documentation
map [1/3]
template<class T , class E > template<class F > decltype(expected_map_impl(std::declval<expected &>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::map(F &&f) & inline
Definition at line 1343 of file expected.h.
map [2/3]
template<class T , class E > template<class F > constexpr decltype(expected_map_impl(std::declval<const expected &>(), std::declval<F &&>())) tl::expected< T, E >::map(F &&f) const & inline constexpr
Definition at line 1355 of file expected.h.
map [3/3]
template<class T , class E > template<class F > constexpr decltype(expected_map_impl(std::declval<const expected &&>(), std::declval<F &&>())) tl::expected< T, E >::map(F &&f) const && inline constexpr
Definition at line 1363 of file expected.h.
map_error [1/4]
template<class T , class E > template<class F > decltype(map_error_impl(std::declval<expected &>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::map_error(F &&f) & inline
Definition at line 1431 of file expected.h.
map_error [2/4]
template<class T , class E > template<class F > decltype(map_error_impl(std::declval<expected &&>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::map_error(F &&f) && inline
Definition at line 1437 of file expected.h.
map_error [3/4]
template<class T , class E > template<class F > constexpr decltype(map_error_impl(std::declval<const expected &>(), std::declval<F &&>())) tl::expected< T, E >::map_error(F &&f) const & inline constexpr
Definition at line 1443 of file expected.h.
map_error [4/4]
template<class T , class E > template<class F > constexpr decltype(map_error_impl(std::declval<const expected &&>(), std::declval<F &&>())) tl::expected< T, E >::map_error(F &&f) const && inline constexpr
Definition at line 1451 of file expected.h.
transform [1/3]
template<class T , class E > template<class F > decltype(expected_map_impl(std::declval<expected &>(), std::declval<F &&>())) TL_EXPECTED_11_CONSTEXPR tl::expected< T, E >::transform(F &&f) & inline
Definition at line 1387 of file expected.h.
transform [2/3]
template<class T , class E > template<class F > constexpr decltype(expected_map_impl(std::declval<const expected &>(), std::declval<F &&>())) tl::expected< T, E >::transform(F &&f) const & inline constexpr
Definition at line 1399 of file expected.h.
transform [3/3]
template<class T , class E > template<class F > constexpr decltype(expected_map_impl(std::declval<const expected &&>(), std::declval<F &&>())) tl::expected< T, E >::transform(F &&f) const && inline constexpr
Definition at line 1407 of file expected.h.
The documentation for this class was generated from the following file:
include/ada/expected.h