Ada: ada::unicode Namespace Reference
ada::unicode Namespace Reference
Includes the declarations for unicode operations.
Functions
ada_really_inline size_t percent_encode_index (const std::string_view input, const uint8_t character_set[])
bool to_ascii (std::optional< std::string > &out, std::string_view plain, size_t first_percent)
std::string to_unicode (std::string_view input)
ada_really_inline bool has_tabs_or_newline (std::string_view user_input) noexcept
ada_really_inline constexpr bool is_forbidden_host_code_point (const char c) noexcept
ada_really_inline constexpr bool contains_forbidden_domain_code_point (const char *input, size_t length) noexcept
ada_really_inline constexpr uint8_t contains_forbidden_domain_code_point_or_upper (const char *input, size_t length) noexcept
ada_really_inline constexpr bool is_forbidden_domain_code_point (const char c) noexcept
ada_really_inline constexpr bool is_alnum_plus (const char c) noexcept
ada_really_inline constexpr bool is_ascii_hex_digit (const char c) noexcept
ada_really_inline constexpr bool is_c0_control_or_space (const char c) noexcept
ada_really_inline constexpr bool is_ascii_tab_or_newline (const char c) noexcept
ada_really_inline ada_constexpr bool is_double_dot_path_segment (const std::string_view input) noexcept
ada_really_inline constexpr bool is_single_dot_path_segment (const std::string_view input) noexcept
ada_really_inline constexpr bool is_lowercase_hex (const char c) noexcept
ada_really_inline unsigned constexpr convert_hex_to_binary (char c) noexcept
std::string percent_decode (const std::string_view input, size_t first_percent)
std::string percent_encode (const std::string_view input, const uint8_t character_set[])
std::string percent_encode (const std::string_view input, const uint8_t character_set[], size_t index)
template<bool append>
bool percent_encode (const std::string_view input, const uint8_t character_set[], std::string &out)
constexpr bool to_lower_ascii (char *input, size_t length) noexcept
constexpr uint64_t broadcast (uint8_t v) noexcept
Variables
static constexpr bool is_forbidden_host_code_point_table []
static constexpr uint8_t is_forbidden_domain_code_point_table []
static constexpr uint8_t is_forbidden_domain_code_point_table_or_upper []
static constexpr bool is_alnum_plus_table []
constexpr std::string_view table_is_double_dot_path_segment []
static constexpr char hex_to_binary_table []
Detailed Description
Includes the declarations for unicode operations.
Includes the definitions for unicode operations.
Function Documentation
broadcast()
constexpr uint64_t ada::unicode::broadcast (uint8_t v) constexpr noexcept
Definition at line 19 of file unicode.cpp.
References ada::parse().
Referenced by has_tabs_or_newline(), and to_lower_ascii().
contains_forbidden_domain_code_point()
ada_really_inline constexpr bool ada::unicode::contains_forbidden_domain_code_point (const char * input, size_t length) constexpr noexcept
Checks if the input contains a forbidden domain code point.
See also
https://url.spec.whatwg.org/#forbidden-domain-code-point
Definition at line 191 of file unicode.cpp.
References is_forbidden_domain_code_point_table, and ada::parse().
Referenced by to_ascii().
contains_forbidden_domain_code_point_or_upper()
ada_really_inline constexpr uint8_t ada::unicode::contains_forbidden_domain_code_point_or_upper (const char * input, size_t length) constexpr noexcept
Checks if the input contains a forbidden domain code point in which case the first bit is set to 1. If the input contains an upper case ASCII letter, then the second bit is set to 1.
See also
https://url.spec.whatwg.org/#forbidden-domain-code-point
Definition at line 225 of file unicode.cpp.
References is_forbidden_domain_code_point_table_or_upper, and ada::parse().
convert_hex_to_binary()
unsigned constexpr ada::unicode::convert_hex_to_binary (char c) constexpr noexcept
Convert hex to binary. Caller is responsible to ensure that the parameter is an hexadecimal digit (0-9, A-F, a-f).
Definition at line 375 of file unicode.cpp.
References hex_to_binary_table, and ada::parse().
Referenced by percent_decode().
has_tabs_or_newline()
ada_really_inline bool ada::unicode::has_tabs_or_newline (std::string_view user_input) noexcept
Checks if the input has tab or newline characters.
Attention
The has_tabs_or_newline function is a bottleneck and it is simple enough that compilers like GCC can 'autovectorize it'.
Definition at line 99 of file unicode.cpp.
References broadcast(), and ada::parse().
Referenced by ada::href_from_file(), and ada::parser::parse_url().
is_alnum_plus()
ada_really_inline constexpr bool ada::unicode::is_alnum_plus (const char c) constexpr noexcept
Checks if the input is alphanumeric, '+', '-' or '.'
Definition at line 282 of file unicode.cpp.
References is_alnum_plus_table, and ada::parse().
Referenced by ada::parser::parse_url(), ada::url::set_protocol(), and ada::url_aggregator::set_protocol().
is_ascii_hex_digit()
ada_really_inline constexpr bool ada::unicode::is_ascii_hex_digit (const char c) constexpr noexcept
An ASCII hex digit is an ASCII upper hex digit or ASCII lower hex digit. An ASCII upper hex digit is an ASCII digit or a code point in the range U+0041 (A) to U+0046 (F), inclusive. An ASCII lower hex digit is an ASCII digit or a code point in the range U+0061 (a) to U+0066 (f), inclusive.
Definition at line 296 of file unicode.cpp.
References ada::parse().
Referenced by percent_decode().
is_ascii_tab_or_newline()
ada_really_inline constexpr bool ada::unicode::is_ascii_tab_or_newline (const char c) constexpr noexcept
Checks if the input is a ASCII tab or newline character.
An ASCII tab or newline is U+0009 TAB, U+000A LF, or U+000D CR.
Definition at line 305 of file unicode.cpp.
References ada::parse().
is_c0_control_or_space()
ada_really_inline constexpr bool ada::unicode::is_c0_control_or_space (const char c) constexpr noexcept
Checks if the input is a C0 control or space character.
A C0 control or space is a C0 control or U+0020 SPACE. A C0 control is a code point in the range U+0000 NULL to U+001F INFORMATION SEPARATOR ONE, inclusive.
Definition at line 301 of file unicode.cpp.
References ada::parse().
Referenced by ada::url::set_port(), and ada::url_aggregator::set_port().
is_double_dot_path_segment()
ada_really_inline ada_constexpr bool ada::unicode::is_double_dot_path_segment (const std::string_view input) noexcept
A double-dot path segment must be ".." or an ASCII case-insensitive match for ".%2e", "%2e.", or "%2e%2e".
Definition at line 313 of file unicode.cpp.
References ada::parse(), and table_is_double_dot_path_segment.
is_forbidden_domain_code_point()
ada_really_inline constexpr bool ada::unicode::is_forbidden_domain_code_point (const char c) constexpr noexcept
Checks if the input is a forbidden domain code point.
See also
https://url.spec.whatwg.org/#forbidden-domain-code-point
Definition at line 186 of file unicode.cpp.
References is_forbidden_domain_code_point_table, and ada::parse().
is_forbidden_host_code_point()
ada_really_inline constexpr bool ada::unicode::is_forbidden_host_code_point (const char c) constexpr noexcept
Checks if the input is a forbidden host code point.
See also
https://url.spec.whatwg.org/#forbidden-host-code-point
Definition at line 147 of file unicode.cpp.
References is_forbidden_host_code_point_table, and ada::parse().
is_lowercase_hex()
ada_really_inline constexpr bool ada::unicode::is_lowercase_hex (const char c) constexpr noexcept
ipv4 character might contain 0-9 or a-f character ranges.
Definition at line 367 of file unicode.cpp.
References ada::parse().
Referenced by ada::checkers::is_ipv4().
is_single_dot_path_segment()
ada_really_inline constexpr bool ada::unicode::is_single_dot_path_segment (const std::string_view input) constexpr noexcept
A single-dot path segment must be "." or an ASCII case-insensitive match for "%2e".
Definition at line 362 of file unicode.cpp.
References ada::parse().
percent_decode()
std::string ada::unicode::percent_decode (const std::string_view input, size_t first_percent)
first_percent should be = input.find('')
Author
Node.js
See also
https://github.com/nodejs/node/blob/main/src/node_url.cc#L245
https://encoding.spec.whatwg.org/#utf-8-decode-without-bom
Definition at line 379 of file unicode.cpp.
References convert_hex_to_binary(), is_ascii_hex_digit(), and ada::parse().
Referenced by to_ascii().
percent_encode() [1/3]
std::string ada::unicode::percent_encode (const std::string_view input, const uint8_t character_set[])
Returns a percent-encoding string whether percent encoding was needed or not.
See also
https://github.com/nodejs/node/blob/main/src/node_url.cc#L226
Definition at line 413 of file unicode.cpp.
References ada::character_sets::bit_at(), ada::character_sets::hex, and ada::parse().
Referenced by ada::parser::parse_url(), ada::url::set_hash(), ada::url::set_password(), ada::url_aggregator::set_password(), ada::url::set_search(), ada::url::set_username(), ada::url_aggregator::set_username(), and ada::url_search_params::to_string().
percent_encode() [2/3]
std::string ada::unicode::percent_encode (const std::string_view input, const uint8_t character_set[], size_t index)
Returns a percent-encoded string version of input, while starting the percent encoding at the provided index.
See also
https://github.com/nodejs/node/blob/main/src/node_url.cc#L226
Definition at line 493 of file unicode.cpp.
References ada::character_sets::bit_at(), ada::character_sets::hex, and ada::parse().
percent_encode() [3/3]
template<bool append> bool ada::unicode::percent_encode (const std::string_view input, const uint8_t character_set[], std::string & out)
Returns true if percent encoding was needed, in which case, we store the percent-encoded content in 'out'. If the boolean 'append' is set to true, the content is appended to 'out'. If percent encoding is not needed, out is left unchanged.
See also
https://github.com/nodejs/node/blob/main/src/node_url.cc#L226
Definition at line 441 of file unicode.cpp.
References ada::character_sets::bit_at(), ada::character_sets::hex, and ada::parse().
percent_encode_index()
ada_really_inline size_t ada::unicode::percent_encode_index (const std::string_view input, const uint8_t character_set[])
Returns the index at which percent encoding should start, or (equivalently), the length of the prefix that does not require percent encoding.
Definition at line 15 of file unicode-inl.h.
References ada::parse().
Referenced by ada::url_aggregator::set_password(), and ada::url_aggregator::set_username().
to_ascii()
bool ada::unicode::to_ascii (std::optional< std::string > & out, std::string_view plain, size_t first_percent)
We receive a UTF-8 string representing a domain name. If the string is percent encoded, we apply percent decoding.
Given a domain, we need to identify its labels. They are separated by label-separators:
U+002E (.) FULL STOP U+FF0E FULLWIDTH FULL STOP U+3002 IDEOGRAPHIC FULL STOP U+FF61 HALFWIDTH IDEOGRAPHIC FULL STOP
They are all mapped to U+002E.
We process each label into a string that should not exceed 63 octets. If the string is already punycode (starts with "xn--"), then we must scan it to look for unallowed code points. Otherwise, if the string is not pure ASCII, we need to transcode it to punycode by following RFC 3454 which requires us to
Map characters (see section 3),
Normalize (see section 4),
Reject forbidden characters,
Check for right-to-left characters and if so, check all requirements (see section 6),
Optionally reject based on unassigned code points (section 7).
The Unicode standard provides a table of code points with a mapping, a list of forbidden code points and so forth. This table is subject to change and will vary based on the implementation. For Unicode 15, the table is at https://www.unicode.org/Public/idna/15.0.0/IdnaMappingTable.txt If you use ICU, they parse this table and map it to code using a Python script.
The resulting strings should not exceed 255 octets according to RFC 1035 section 2.3.4. ICU checks for label size and domain size, but these errors are ignored.
See also
https://url.spec.whatwg.org/#concept-domain-to-ascii
Definition at line 475 of file unicode.cpp.
References contains_forbidden_domain_code_point(), ada::parse(), percent_decode(), and ada::idna::to_ascii().
to_lower_ascii()
constexpr bool ada::unicode::to_lower_ascii (char * input, size_t length) constexpr noexcept
Lowers the string in-place, assuming that the content is ASCII. Return true if the content was ASCII.
Definition at line 23 of file unicode.cpp.
References broadcast(), and ada::parse().
to_unicode()
std::string ada::unicode::to_unicode (std::string_view input)
See also
https://www.unicode.org/reports/tr46/#ToUnicode
Definition at line 508 of file unicode.cpp.
References ada::parse(), and ada::idna::to_unicode().
Variable Documentation
hex_to_binary_table
constexpr char ada::unicode::hex_to_binary_table[] static constexpr
Initial value:
= {
    0,  1,  2,  3,  4, 5, 6, 7, 8, 9, 0, 0,  0,  0,  0,  0,  0, 10, 11,
    12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0, 0,  0,
    0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 13, 14, 15}
Definition at line 371 of file unicode.cpp.
Referenced by convert_hex_to_binary().
is_alnum_plus_table
constexpr bool ada::unicode::is_alnum_plus_table[] static constexpr
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 267 of file unicode.cpp.
Referenced by is_alnum_plus().
is_forbidden_domain_code_point_table
constexpr uint8_t ada::unicode::is_forbidden_domain_code_point_table[] static constexpr
Initial value:
= {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
Definition at line 171 of file unicode.cpp.
Referenced by contains_forbidden_domain_code_point(), and is_forbidden_domain_code_point().
is_forbidden_domain_code_point_table_or_upper
constexpr uint8_t ada::unicode::is_forbidden_domain_code_point_table_or_upper[] static constexpr
Initial value:
= {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
Definition at line 207 of file unicode.cpp.
Referenced by contains_forbidden_domain_code_point_or_upper().
is_forbidden_host_code_point_table
constexpr bool ada::unicode::is_forbidden_host_code_point_table[] static constexpr
Initial value:
= {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 133 of file unicode.cpp.
Referenced by is_forbidden_host_code_point().
table_is_double_dot_path_segment
constexpr std::string_view ada::unicode::table_is_double_dot_path_segment[] constexpr
Initial value:
= {
    "..", "%2e.", ".%2e", "%2e%2e"}
Definition at line 310 of file unicode.cpp.
Referenced by is_double_dot_path_segment().