name: Benchmark

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Install ICU
        run: sudo apt-get install -y libicu-dev pkg-config
      - name: Install curl
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install boost
        uses: MarkusJx/install-boost@d175e516e6d321b68ff67afecf7da5e7c53c16f7 # v2.4.3
        with:
          boost_version: 1.81.0
      - name: Setup Ninja
        run: sudo apt-get install ninja-build

      - name: Prepare
        run: cmake -G Ninja -B build -DADA_BENCHMARKS=ON
      - name: Build
        run: cmake --build build -j=2

      - name: Run default benchmark
        run: cd build && sudo benchmarks/bench --benchmark_format=json | tee ../default_benchmark_result.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@c3efd4d54319dbc90622069cc273cba59b46abbf # v1.15.0
        with:
          name: Benchmark
          tool: 'googlecpp'
          output-file-path: default_benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anonrig @lemire'

      - name: Run WPT benchmark
        run: cd build && sudo benchmarks/wpt_bench tests/wpt/urltestdata.json --benchmark_format=json | tee ../wpt_benchmark_result.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@c3efd4d54319dbc90622069cc273cba59b46abbf # v1.15.0
        with:
          name: Web Platform Tests
          tool: 'googlecpp'
          output-file-path: wpt_benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anonrig @lemire'

      - name: Run BBC benchmark
        run: cd build && sudo benchmarks/bbc_bench --benchmark_format=json | tee ../bbc_benchmark_result.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@c3efd4d54319dbc90622069cc273cba59b46abbf # v1.15.0
        with:
          name: BBC URLs
          tool: 'googlecpp'
          output-file-path: bbc_benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anonrig @lemire'
