name: Ubuntu 22.04 CI (GCC 12 SANITIZED)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v3
      - name: Install ICU
        run: sudo apt-get install -y libicu-dev pkg-config
      - name: Setup Ninja
        run: sudo apt-get install ninja-build
      - name: Use cmake
        run: |
          mkdir build && cd build
      - name: Prepare
        working-directory: build
        run: CXX=g++-12 cmake -DADA_SANITIZE=ON -DBUILD_SHARED_LIBS=${{matrix.shared}} -G Ninja ..
      - name: Build
        working-directory: build
        run: cmake --build . --target wpt_tests --target basic_fuzzer
      - name: Test
        working-directory: build
        run: ctest --output-on-failure
