name: Ubuntu 22.04 CI (LLVM 14)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v3
      - name: Install ICU
        run: sudo apt-get install -y libicu-dev pkg-config
      - name: Install curl
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
      - name: Prepare
        run: |
          mkdir build && cd build &&
          CXX=clang++-14 cmake -DBUILD_SHARED_LIBS=${{matrix.shared}} ..
      - name: Build
        working-directory: build
        run: cmake --build .
      - name: Test
        working-directory: build
        run: ctest --output-on-failure
