name: Ubuntu 22.04 CI (GCC 12 SANITIZED)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - {shared: ON}
          - {shared: OFF}
    steps:
      - uses: actions/checkout@v3
      - name: Install ICU
        run: sudo apt-get install -y libicu-dev pkg-config
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          CXX=g++-12 cmake -DADA_SANITIZE=ON -DBUILD_SHARED_LIBS=${{matrix.shared}} ..  &&
          cmake --build . --target wpt_tests --target basic_fuzzer  &&
          ctest --output-on-failure
