Ada: ada::url_pattern_component< regex_provider > Class Template Reference
ada::url_pattern_component< regex_provider > Class Template Reference
#include <url_pattern.h>
Public Member Functions
url_pattern_component ()=default
url_pattern_component (std::string &&new_pattern, typename regex_provider::regex_type &&new_regexp, std::vector< std::string > &&new_group_name_list, bool new_has_regexp_groups)
url_pattern_component_result create_component_match_result (std::string &&input, std::vector< std::optional< std::string > > &&exec_result)
template<url_pattern_encoding_callback F>
tl::expected< url_pattern_component< regex_provider >, errors > compile (std::string_view input, F &encoding_callback, url_pattern_compile_component_options &options)
Static Public Member Functions
template<url_pattern_encoding_callback F>
static tl::expected< url_pattern_component, errors > compile (std::string_view input, F &encoding_callback, url_pattern_compile_component_options &options)
Public Attributes
regex_provider::regex_type regexp {}
std::string pattern {}
std::vector< std::string > group_name_list {}
bool has_regexp_groups = false
Detailed Description
template<url_pattern_regex::regex_concept regex_provider>
class ada::url_pattern_component< regex_provider >
Definition at line 150 of file url_pattern.h.
Constructor & Destructor Documentation
url_pattern_component() [1/2]
template<url_pattern_regex::regex_concept regex_provider> ada::url_pattern_component< regex_provider >::url_pattern_component () default
Referenced by compile().
url_pattern_component() [2/2]
template<url_pattern_regex::regex_concept regex_provider> ada::url_pattern_component< regex_provider >::url_pattern_component (std::string && new_pattern, typename regex_provider::regex_type && new_regexp, std::vector< std::string > && new_group_name_list, bool new_has_regexp_groups) inline
Definition at line 156 of file url_pattern.h.
References group_name_list, has_regexp_groups, pattern, and regexp.
Member Function Documentation
compile() [1/2]
template<url_pattern_regex::regex_concept regex_provider> template<url_pattern_encoding_callback F> tl::expected< url_pattern_component< regex_provider >, errors > ada::url_pattern_component< regex_provider >::compile (std::string_view input, F & encoding_callback, url_pattern_compile_component_options & options)
Definition at line 143 of file url_pattern-inl.h.
References ada::url_pattern_helpers::generate_pattern_string(), ada::url_pattern_helpers::generate_regular_expression_and_name_list(), has_regexp_groups, ada::url_pattern_compile_component_options::ignore_case, ada::url_pattern_helpers::parse_pattern_string(), ada::type_error, and url_pattern_component().
compile() [2/2]
template<url_pattern_regex::regex_concept regex_provider> template<url_pattern_encoding_callback F> static tl::expected< url_pattern_component, errors > ada::url_pattern_component< regex_provider >::compile (std::string_view input, F & encoding_callback, url_pattern_compile_component_options & options) static
References create_component_match_result(), and url_pattern_component().
Referenced by ada::url_pattern_helpers::constructor_string_parser< regex_provider >::compute_protocol_matches_special_scheme_flag(), and ada::url_aggregator::parse_url_pattern_impl.
create_component_match_result()
template<url_pattern_regex::regex_concept regex_provider> url_pattern_component_result ada::url_pattern_component< regex_provider >::create_component_match_result (std::string && input, std::vector< std::optional< std::string > > && exec_result)
Definition at line 32 of file url_pattern-inl.h.
References group_name_list.
Referenced by compile().
Member Data Documentation
group_name_list
template<url_pattern_regex::regex_concept regex_provider> std::vector<std::string> ada::url_pattern_component< regex_provider >::group_name_list {}
Definition at line 190 of file url_pattern.h.
Referenced by create_component_match_result(), and url_pattern_component().
has_regexp_groups
template<url_pattern_regex::regex_concept regex_provider> bool ada::url_pattern_component< regex_provider >::has_regexp_groups = false
Definition at line 191 of file url_pattern.h.
Referenced by compile(), and url_pattern_component().
pattern
template<url_pattern_regex::regex_concept regex_provider> std::string ada::url_pattern_component< regex_provider >::pattern {}
Definition at line 189 of file url_pattern.h.
Referenced by url_pattern_component().
regexp
template<url_pattern_regex::regex_concept regex_provider> regex_provider::regex_type ada::url_pattern_component< regex_provider >::regexp {}
Definition at line 188 of file url_pattern.h.
Referenced by ada::url_pattern_helpers::protocol_component_matches_special_scheme(), and url_pattern_component().
The documentation for this class was generated from the following files:
include/ada/url_pattern.h
include/ada/url_pattern-inl.h